<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class QualifierProfilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('qualifier_profiles')->delete();
        
        \DB::table('qualifier_profiles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'email' => 'jellaneberioso@gmail.com',
                'firstname' => 'JELLANE LEIGH',
                'lastname' => 'BERIOSO',
                'middlename' => 'QUIMNO',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9455936342',
                'birthday' => '2005-01-28',
                'qualifier_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'email' => 'nixstationeryzambo7000@gmail.com',
                'firstname' => 'HANNAH NICOLE',
                'lastname' => 'PATRICIO',
                'middlename' => 'AMIGO',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9757562117',
                'birthday' => '2004-10-02',
                'qualifier_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'email' => 'irenelucilleee@gmail.com',
                'firstname' => 'IRENE LUCILLE',
                'lastname' => 'GARCIA',
                'middlename' => 'GO',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9677212599',
                'birthday' => '2004-05-11',
                'qualifier_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'email' => 'yasminabduljalil635@gmail.com',
                'firstname' => 'YASMIN',
                'lastname' => 'ABDULJALIL',
                'middlename' => 'CUBOL',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9081064010',
                'birthday' => '2005-02-17',
                'qualifier_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'email' => 'vllrjasmine@gmail.com',
                'firstname' => 'JASMINE',
                'lastname' => 'VILLAR',
                'middlename' => 'SALATAN',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9639389083',
                'birthday' => '2005-01-20',
                'qualifier_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'email' => 'nurhayatique@gmail.com',
                'firstname' => 'NURHAYATI',
                'lastname' => 'MOH`D RAFFY QUE',
                'middlename' => 'ABDULHAIH',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9757620235',
                'birthday' => '2005-06-29',
                'qualifier_id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'email' => 'joshuaalbay16@gmail.com',
                'firstname' => 'JOSHUA ANGEL',
                'lastname' => 'ALBAY',
                'middlename' => 'CARAECLE',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9364404937',
                'birthday' => '2004-12-16',
                'qualifier_id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'email' => 'arthon.godito@gmail.com',
                'firstname' => 'LITO ARTHON',
                'lastname' => 'GODITO',
                'middlename' => 'RECAMARA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9212505350',
                'birthday' => '2004-11-06',
                'qualifier_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'email' => 'romanoangelo321@gmail.com',
                'firstname' => 'ANGELO JAMES',
                'lastname' => 'ROMANO',
                'middlename' => 'JUMALON',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9187271741',
                'birthday' => '2004-05-04',
                'qualifier_id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'email' => 'jaladkhad@gmail.com',
                'firstname' => 'ACLAN',
                'lastname' => 'JALAD',
                'middlename' => 'ABDULLA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9567183219',
                'birthday' => '2004-12-07',
                'qualifier_id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'email' => 'alquizaanroemmanuel@gmail.com',
                'firstname' => 'HIMPON',
                'lastname' => 'ALQUIZA',
                'middlename' => 'DOMUGHO',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9670238837',
                'birthday' => '2005-03-08',
                'qualifier_id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'email' => 'randyhibaya4@gmail.com',
                'firstname' => 'HIMPON',
                'lastname' => 'HIBAYA',
                'middlename' => 'POQUITA',
                'suffix' => 'JR.',
                'sex' => 'M',
                'contact_no' => '9109002785',
                'birthday' => '2004-04-04',
                'qualifier_id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'email' => 'angelgracearapoc04@gmail.com',
                'firstname' => 'ANGEL GRACE',
                'lastname' => 'ARAPOC',
                'middlename' => 'POLIPOG',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9082962945',
                'birthday' => '2004-09-15',
                'qualifier_id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'email' => 'neilchristiani2341@gmail.com',
                'firstname' => 'NEIL CHRISTIAN',
                'lastname' => 'RANOCO',
                'middlename' => 'VILLAROSA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9058737484',
                'birthday' => '2004-06-30',
                'qualifier_id' => 14,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'email' => 'porillo2004@gmail.com',
                'firstname' => 'JOSHUA',
                'lastname' => 'PORILLO',
                'middlename' => 'BARTOLO',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9383093931',
                'birthday' => '2004-12-25',
                'qualifier_id' => 15,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'email' => 'vallesmar311@gmail.com',
                'firstname' => 'MARIEL',
                'lastname' => 'VALLES',
                'middlename' => 'BANDALA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9317189973',
                'birthday' => '2005-03-11',
                'qualifier_id' => 16,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'email' => 'gabtiongson2004@gmail.com',
                'firstname' => 'GABRIEL JUANITO',
                'lastname' => 'TIONGSON',
                'middlename' => 'GALICHA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9060043155',
                'birthday' => '2004-08-31',
                'qualifier_id' => 17,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'email' => 'dellavakenvinzel@gmail.com',
                'firstname' => 'KEN VINZEL',
                'lastname' => 'DELLAVA',
                'middlename' => 'EBOL',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9552142342',
                'birthday' => '2005-02-21',
                'qualifier_id' => 18,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'email' => 'enriquezaprilmae44@gmail.com',
                'firstname' => 'APRIL MAE',
                'lastname' => 'ENRIQUEZ',
                'middlename' => 'MARUJI',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => NULL,
                'birthday' => '2005-04-26',
                'qualifier_id' => 19,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'email' => 'pepitoandrew52@gmail.com',
                'firstname' => 'DAVE ANDREW',
                'lastname' => 'PEPITO',
                'middlename' => 'LEMOSNERO',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9384014859',
                'birthday' => '2005-03-09',
                'qualifier_id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'email' => 'euwanprias44@gmail.com',
                'firstname' => 'EUWAN TYRONE',
                'lastname' => 'PRIAS',
                'middlename' => 'BAUGBOG',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9654008462',
                'birthday' => '2005-05-16',
                'qualifier_id' => 21,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'email' => 'seanjren@gmail.com',
                'firstname' => 'SEAN LAUREN',
                'lastname' => 'JAYME',
                'middlename' => 'LITANG',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9983648494',
                'birthday' => '2004-09-22',
                'qualifier_id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'email' => 'adriannejoshv@gmail.com',
                'firstname' => 'ADRIANNE JOSH',
                'lastname' => 'VEGA',
                'middlename' => 'SUMILHIG',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9178230466',
                'birthday' => '2004-05-09',
                'qualifier_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'email' => 'sailentadwgeh@gmail.com',
                'firstname' => 'IAN HENDRICK',
                'lastname' => 'PUGOY',
                'middlename' => 'SOLLANO',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9661887232',
                'birthday' => '2004-10-29',
                'qualifier_id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'email' => 'handuganginoandrie@gmail.com',
                'firstname' => 'GINO ANDRIE',
                'lastname' => 'HANDUGAN',
                'middlename' => 'RICARDO',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9479571759',
                'birthday' => '2004-11-30',
                'qualifier_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'email' => 'dumbania81@gmail.com',
                'firstname' => 'DARRYL DAVE',
                'lastname' => 'UMBAÑA',
                'middlename' => 'BALINGIT',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9129054260',
                'birthday' => '2005-07-11',
                'qualifier_id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'email' => 'luchanaladygayle@gmail.com',
                'firstname' => 'LADY GAYLE',
                'lastname' => 'LUCHANA',
                'middlename' => 'GUMBAN',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9465053646',
                'birthday' => '2005-02-05',
                'qualifier_id' => 27,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'email' => 'josephcenizagabriel@gmail.com',
                'firstname' => 'JOSEPH GABRIEL',
                'lastname' => 'CENIZA',
                'middlename' => 'NARAG',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9811164717',
                'birthday' => '2005-05-05',
                'qualifier_id' => 28,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'email' => 'jayveannqnatuil@gmail.com',
                'firstname' => 'JAYVE ANN QUEENY',
                'lastname' => 'NATUIL',
                'middlename' => 'MASONG',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9073593003',
                'birthday' => '2004-10-17',
                'qualifier_id' => 29,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'email' => 'gkmagsayo@gmail.com',
                'firstname' => 'GEORGE KENT',
                'lastname' => 'MAGSAYO',
                'middlename' => 'HOCOY',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9615264638',
                'birthday' => '2005-06-23',
                'qualifier_id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'email' => 'samuelestrellon18@gmail.com',
                'firstname' => 'SAMUEL',
                'lastname' => 'ESTRELLON',
                'middlename' => 'HILAGA',
                'suffix' => 'JR.',
                'sex' => 'M',
                'contact_no' => '9383748250',
                'birthday' => '2005-12-18',
                'qualifier_id' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'email' => 'joshua12galamiton04@gmail.com',
                'firstname' => 'JOSHUA GENESIS',
                'lastname' => 'GALAMITON',
                'middlename' => 'CUIZON',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9164102291',
                'birthday' => '2004-07-12',
                'qualifier_id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'email' => 'mautejano10@gmail.com',
                'firstname' => 'MAURICE DAWN',
                'lastname' => 'TEJANO',
                'middlename' => 'CORDA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9690294194',
                'birthday' => '2004-04-10',
                'qualifier_id' => 33,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'email' => 'alagenionicolekeith@gmail.com',
                'firstname' => 'NICOLE KEITH',
                'lastname' => 'ALAGENIO',
                'middlename' => 'SUMALINOG',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9276486580',
                'birthday' => '2004-09-28',
                'qualifier_id' => 34,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'email' => 'ninotapiz@gmail.com',
                'firstname' => 'NIÑO NEIL',
                'lastname' => 'TAPIZ',
                'middlename' => 'PASTER',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9517916396',
                'birthday' => '2004-10-02',
                'qualifier_id' => 35,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'email' => 'calihswaegg@gmail.com',
                'firstname' => 'HACALIAH',
                'lastname' => 'PEDUHAN',
                'middlename' => 'ESTOMATA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9166134283',
                'birthday' => '2004-03-22',
                'qualifier_id' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'email' => 'orepsorp54@gmail.com',
                'firstname' => 'ANDREA FE',
                'lastname' => 'PROSPERO',
                'middlename' => 'PATALINGHUG',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9187276344',
                'birthday' => '2004-11-30',
                'qualifier_id' => 37,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'email' => 'jamespaulinequijano@gmail.com',
                'firstname' => 'JAMES PAULINE',
                'lastname' => 'QUIJANO',
                'middlename' => 'RAMAYLA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9700483597',
                'birthday' => '2005-10-04',
                'qualifier_id' => 38,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'email' => 'richessminique357@gmail.com',
                'firstname' => 'AMANIY',
                'lastname' => 'AYAON',
                'middlename' => 'TANDICO',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9653348848',
                'birthday' => '2005-09-13',
                'qualifier_id' => 39,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'email' => 'bexcreatives@gmail.com',
                'firstname' => 'WILFRED KHAMIS',
                'lastname' => 'YBAÑEZ',
                'middlename' => 'CANTURIAS',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9129653555',
                'birthday' => '2004-03-20',
                'qualifier_id' => 40,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'email' => 'micahalexis2004@gmail.com',
                'firstname' => 'MICAH ALEXIS',
                'lastname' => 'TURADO',
                'middlename' => 'REYES',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9104205925',
                'birthday' => '2004-11-04',
                'qualifier_id' => 41,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'email' => 'jeshrogarcia1007@gmail.com',
                'firstname' => 'JESHRO KELLY',
                'lastname' => 'GARCIA',
                'middlename' => 'MONTER',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9534502620',
                'birthday' => '2004-12-23',
                'qualifier_id' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'email' => 'zycardeno@gmail.com',
                'firstname' => 'ZYLA MARIE',
                'lastname' => 'CARDEÑO',
                'middlename' => 'VEDEJA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9106138499',
                'birthday' => '2004-09-01',
                'qualifier_id' => 43,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'email' => 'mercadoeraphaelangelu@gmail.com',
                'firstname' => 'RAPHAEL ANGELU',
                'lastname' => 'MERCADO',
                'middlename' => 'ERASMO',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9475310624',
                'birthday' => '2004-10-03',
                'qualifier_id' => 44,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'email' => 'franzmichaeldiao15@gmail.com',
                'firstname' => 'FRANZ MICHAEL',
                'lastname' => 'DIAO',
                'middlename' => 'JUMAWAN',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9998914717',
                'birthday' => '2005-01-14',
                'qualifier_id' => 45,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'email' => 'nasreenfatimahussain@gmail.com',
                'firstname' => 'NASREEN FATIMA',
                'lastname' => 'HUSSAIN',
                'middlename' => 'VALLEJOS',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9922739492',
                'birthday' => '2004-12-26',
                'qualifier_id' => 46,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'email' => 'rrecs2004@gmail.com',
                'firstname' => 'RAFFY',
                'lastname' => 'RECOSOSA',
                'middlename' => 'REALIZA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9763371550',
                'birthday' => '2004-07-08',
                'qualifier_id' => 47,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'email' => 'kenmac06.km@gmail.com',
                'firstname' => 'KEN',
                'lastname' => 'MACARAEG',
                'middlename' => 'OLAIVAR',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9184866797',
                'birthday' => '2005-01-06',
                'qualifier_id' => 48,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'email' => 'altkian2@gmail.com',
                'firstname' => 'NADZWA',
                'lastname' => 'USMAN',
                'middlename' => 'PARADJI',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9751762529',
                'birthday' => '2005-10-28',
                'qualifier_id' => 49,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'email' => 'johngodwinbuenaflor22@gmail.com',
                'firstname' => 'JOHN GODWIN',
                'lastname' => 'BUENAFLOR',
                'middlename' => 'ROJAS',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9352361722',
                'birthday' => '2004-11-20',
                'qualifier_id' => 50,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'email' => 'julesbugawan7@gmail.com',
                'firstname' => 'JULES',
                'lastname' => 'BUGAWAN',
                'middlename' => 'NAMOCATCAT',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9307662238',
                'birthday' => '2004-07-03',
                'qualifier_id' => 51,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'email' => 'girliemagto20@gmail.com',
                'firstname' => 'GIRLIE',
                'lastname' => 'MAGTO',
                'middlename' => 'AYUDTOD',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9465591145',
                'birthday' => '2005-03-20',
                'qualifier_id' => 52,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'email' => 'avsinramoncito@gmail.com',
                'firstname' => 'AVSIN',
                'lastname' => 'RAMONCITO',
                'middlename' => 'ALIH',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9977918491',
                'birthday' => '2004-12-05',
                'qualifier_id' => 53,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'email' => 'danieltipohian2505@gmail.com',
                'firstname' => 'DANIEL IAN',
                'lastname' => 'TIPOH',
                'middlename' => 'GENER',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9074601649',
                'birthday' => '2005-02-25',
                'qualifier_id' => 54,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'email' => 'jp.jasper01904@gmail.com',
                'firstname' => 'JASPER',
                'lastname' => 'ORAÑOLA',
                'middlename' => 'PANGILAYAN',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9518460189',
                'birthday' => '2004-09-01',
                'qualifier_id' => 55,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'email' => 'howpaclijan@gmail.com',
                'firstname' => 'HOWARD GABRIEL',
                'lastname' => 'PACLIJAN',
                'middlename' => 'YAP',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9338151245',
                'birthday' => '2005-05-08',
                'qualifier_id' => 56,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'email' => 'sinangoteag008@gmail.com',
                'firstname' => 'ANIKA GRACE',
                'lastname' => 'SINANGOTE',
                'middlename' => 'NUENA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9207856515',
                'birthday' => '2004-09-28',
                'qualifier_id' => 57,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'email' => 'kemperador25@gmail.com',
                'firstname' => 'MICHAEL EARL KENNETH',
                'lastname' => 'BERIOSO',
                'middlename' => 'SEGOVIA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9979643306',
                'birthday' => '2005-02-25',
                'qualifier_id' => 58,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'email' => 'joycealegrado23@gmail.com',
                'firstname' => 'JOYCE MARIE',
                'lastname' => 'ALEGRADO',
                'middlename' => 'DOLIENTE',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9504689764',
                'birthday' => '2004-11-23',
                'qualifier_id' => 59,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'email' => 'sabanillo111@gmail.com',
                'firstname' => 'JHON KYLE',
                'lastname' => 'SABANILLO',
                'middlename' => 'GEMENTIZA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9355729189',
                'birthday' => '2005-01-04',
                'qualifier_id' => 60,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'email' => 'denzmath110@gmail.com',
                'firstname' => 'DENNIS',
                'lastname' => 'DAYAGANON',
                'middlename' => 'MONTALBA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9650581243',
                'birthday' => '2004-11-10',
                'qualifier_id' => 61,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'email' => 'josh.mamu.dadu@gmail.com',
                'firstname' => 'JOSHUA CEASAR IAN',
                'lastname' => 'PERALTA',
                'middlename' => 'ABIDEN',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9703030918',
                'birthday' => '2004-06-20',
                'qualifier_id' => 62,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'email' => 'chrystianquicoy@gmail.com',
                'firstname' => 'CHRYSTIAN PAUL',
                'lastname' => 'QUICOY',
                'middlename' => 'SEMENSE',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9693342014',
                'birthday' => '2004-06-20',
                'qualifier_id' => 63,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'email' => 'tyronepareno27@gmail.com',
                'firstname' => 'LEIANN TYRONE',
                'lastname' => 'CAPALA',
                'middlename' => 'PARREÑO',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9218561974',
                'birthday' => '2005-09-27',
                'qualifier_id' => 64,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'email' => 'enriquezrose719@gmail.com',
                'firstname' => 'APRIL ROSE',
                'lastname' => 'ENRIQUEZ',
                'middlename' => 'MARUJI',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9555905961',
                'birthday' => '2005-04-26',
                'qualifier_id' => 65,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'email' => 'allarexdaniel123@gmail.com',
                'firstname' => 'REX DANIEL',
                'lastname' => 'ALLA',
                'middlename' => 'SARMIENTO',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9261839592',
                'birthday' => '2004-07-26',
                'qualifier_id' => 66,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'email' => 'cythelmanait@gmail.com',
                'firstname' => 'CYTHEL MARIE',
                'lastname' => 'MANAIT',
                'middlename' => 'RUSIANA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9264325654',
                'birthday' => '2005-07-09',
                'qualifier_id' => 67,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'email' => 'heartmanuel433@gmail.com',
                'firstname' => 'HEART',
                'lastname' => 'MANUEL',
                'middlename' => 'ENANORIA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => NULL,
                'birthday' => '2005-12-26',
                'qualifier_id' => 68,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'email' => 'royajanemontiel@gmail.com',
                'firstname' => 'ROYA JANE',
                'lastname' => 'MONTIEL',
                'middlename' => 'BUTALID',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9550577251',
                'birthday' => '2005-10-23',
                'qualifier_id' => 69,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'email' => 'elaizajazmine@gmail.com',
                'firstname' => 'JAZMINE ELAIZA',
                'lastname' => 'LUIS',
                'middlename' => 'LAJA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9661568525',
                'birthday' => '2005-01-03',
                'qualifier_id' => 70,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'email' => 'shansarayan@gmail.com',
                'firstname' => 'SHAN MICHAEL',
                'lastname' => 'SARAYAN',
                'middlename' => 'ALISACA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9122867816',
                'birthday' => '2004-09-29',
                'qualifier_id' => 71,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'email' => 'lyleralburo@su.edu.ph',
                'firstname' => 'LYLE',
                'lastname' => 'ALBURO',
                'middlename' => 'RODRIGUEZ',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9606693052',
                'birthday' => '2005-01-28',
                'qualifier_id' => 72,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'email' => 'ellicaarnold4official@gmail.com',
                'firstname' => 'ARNOLD',
                'lastname' => 'ELLICA',
                'middlename' => 'BASILIO',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9274933953',
                'birthday' => '2004-07-10',
                'qualifier_id' => 73,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'email' => 'hannahgracetulabing@gmail.com',
                'firstname' => 'HANNAH GRACE',
                'lastname' => 'TULABING',
                'middlename' => 'SALUTA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9097207890',
                'birthday' => '2005-02-24',
                'qualifier_id' => 74,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'email' => 'aquinoruainihashim@gmail.com',
                'firstname' => 'RUAINI',
                'lastname' => 'AQUINO',
                'middlename' => 'HASHIM',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9979429993',
                'birthday' => '2005-07-19',
                'qualifier_id' => 75,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'email' => 'intongheather@gmail.com',
                'firstname' => 'HEATHER SIMONETTE ROSE',
                'lastname' => 'INTONG',
                'middlename' => 'MOSQUEDA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9267544109',
                'birthday' => '2004-12-04',
                'qualifier_id' => 76,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'email' => 'ajhayudini.school@gmail.com',
                'firstname' => 'AYESHA JULIA',
                'lastname' => 'HAYUDINI',
                'middlename' => 'JUHASAN',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9270180095',
                'birthday' => '2005-08-25',
                'qualifier_id' => 77,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'email' => 'cyd.oral25@gmail.com',
                'firstname' => 'CLARENCE JAMES',
                'lastname' => 'ORAL',
                'middlename' => 'DUNGGAY',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9203531940',
                'birthday' => '2005-05-25',
                'qualifier_id' => 78,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'email' => 'crystalclairecaylaluad04@gmail.com',
                'firstname' => 'CRYSTAL CLAIRE',
                'lastname' => 'CAYLALUAD',
                'middlename' => 'AGUILOR',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9694518357',
                'birthday' => '2004-10-29',
                'qualifier_id' => 79,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'email' => 'tabanagjimbert@gmail.com',
                'firstname' => 'JIMBERT',
                'lastname' => 'TABAÑAG',
                'middlename' => 'LAQUINON',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9816937807',
                'birthday' => '2004-08-25',
                'qualifier_id' => 80,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'email' => 'jeanniza.sulit@gmail.com',
                'firstname' => 'RUDJEAN RUTH',
                'lastname' => 'SULIT',
                'middlename' => 'RELUYA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9293694553',
                'birthday' => '2004-04-01',
                'qualifier_id' => 81,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'email' => 'kiloumanjaro@gmail.com',
                'firstname' => 'KINT LOUISE',
                'lastname' => 'BORBANO',
                'middlename' => NULL,
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9105455147',
                'birthday' => '2004-01-10',
                'qualifier_id' => 82,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'email' => 'hazel.sarabia04@gmail.com',
                'firstname' => 'HAZEL',
                'lastname' => 'SARABIA',
                'middlename' => 'ALVARICO',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9050889970',
                'birthday' => '2004-11-10',
                'qualifier_id' => 83,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'email' => 'kristylirramae22@gmail.com',
                'firstname' => 'KRISTYL IRRA MAE',
                'lastname' => 'ELCAMEL',
                'middlename' => 'CALASANG',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9089725775',
                'birthday' => '2004-08-22',
                'qualifier_id' => 84,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'email' => 'viagedorcrystal@gmail.com',
                'firstname' => 'CRYSTAL KYLLA',
                'lastname' => 'VIAGEDOR',
                'middlename' => 'BANTIGUE',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9396963193',
                'birthday' => '2004-09-15',
                'qualifier_id' => 85,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'email' => 'gyzerlumingo@gmail.com',
                'firstname' => 'GYZER REIL',
                'lastname' => 'LUMINGO',
                'middlename' => 'ABUCAY',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9700212589',
                'birthday' => '2004-12-06',
                'qualifier_id' => 86,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'email' => 'ericakae.14@gmail.com',
                'firstname' => 'ERICA KAE',
                'lastname' => 'MENIL',
                'middlename' => 'ANSALI',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9380215943',
                'birthday' => '2004-12-24',
                'qualifier_id' => 87,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'email' => 'havilahmardiflores28@gmail.com',
                'firstname' => 'HAVILAH MARDI',
                'lastname' => 'FLORES',
                'middlename' => 'CINCO',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9980560213',
                'birthday' => '2004-09-28',
                'qualifier_id' => 88,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'email' => 'lokichelsybalucan@gmail.com',
                'firstname' => 'CHELSY',
                'lastname' => 'BALUCAN',
                'middlename' => 'MOSQUISA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9155693039',
                'birthday' => '2005-04-10',
                'qualifier_id' => 89,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'email' => 'kimmyvictus@gmail.com',
                'firstname' => 'RYAN',
                'lastname' => 'ESCODERO',
                'middlename' => 'PAINAGA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9364635344',
                'birthday' => '2005-06-20',
                'qualifier_id' => 90,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'email' => 'haipaharuddin@gmail.com',
                'firstname' => 'FAIRUZ',
                'lastname' => 'HARUDDIN',
                'middlename' => 'CANALON',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9755253665',
                'birthday' => '2005-02-25',
                'qualifier_id' => 91,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'email' => 'jasmineshayne00@gmail.com',
                'firstname' => 'JASMINE SHAYNE',
                'lastname' => 'BODIONGAN',
                'middlename' => 'BEDUYA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9103829337',
                'birthday' => '2005-02-01',
                'qualifier_id' => 92,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'email' => 'shaniajrubio@gmail.com',
                'firstname' => 'SHANIA',
                'lastname' => 'RUBIO',
                'middlename' => 'JAMAROLIN',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9687164115',
                'birthday' => '2004-09-03',
                'qualifier_id' => 93,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'email' => 'kristaabiiigail@gmail.com',
                'firstname' => 'KRISTA ABEGAIL',
                'lastname' => 'FONTANILLA',
                'middlename' => 'ESTRELLA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9950981343',
                'birthday' => '2004-10-17',
                'qualifier_id' => 94,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'email' => 'cabasaglady@gmail.com',
                'firstname' => 'LADY CHARIZ',
                'lastname' => 'CABASAG',
                'middlename' => 'BUSTALIÑO',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9610122054',
                'birthday' => '2004-06-10',
                'qualifier_id' => 95,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'email' => 'lexineandrea12@gmail.com',
                'firstname' => 'LEXINE ANDREA',
                'lastname' => 'CAVAN',
                'middlename' => 'MACUTE',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9763003557',
                'birthday' => '2004-09-28',
                'qualifier_id' => 96,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'email' => 'marialjimenez@su.edu.ph',
                'firstname' => 'MARIA DAYAMINA',
                'lastname' => 'JIMENEZ',
                'middlename' => 'LAVADOR',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9294829360',
                'birthday' => '2004-10-13',
                'qualifier_id' => 97,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'email' => 'christiang98434@gmail.com',
                'firstname' => 'CHRISTIAN',
                'lastname' => 'OMPAY',
                'middlename' => 'GALLEGO',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9517920791',
                'birthday' => '2004-12-29',
                'qualifier_id' => 98,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'email' => 'banaanrosell@gmail.com',
                'firstname' => 'REIZEL',
                'lastname' => 'BANA-AN',
                'middlename' => 'INTO',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9925230827',
                'birthday' => '2005-07-02',
                'qualifier_id' => 99,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'email' => 'kccamelotes@gmail.com',
                'firstname' => 'KLAIRE',
                'lastname' => 'CAMELOTES',
                'middlename' => 'RECAPENTE',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9684578455',
                'birthday' => '2004-10-28',
                'qualifier_id' => 100,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'email' => 'tumale.lorrainejasmine.d@gmail.com',
                'firstname' => 'LORRAINE JASMINE',
                'lastname' => 'TUMALE',
                'middlename' => 'DUHAYLONGSOD',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => NULL,
                'birthday' => '2004-09-13',
                'qualifier_id' => 101,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'email' => 'joannemaryzc@gmail.com',
                'firstname' => 'JOANNE MARYZ',
                'lastname' => 'CABATINGAN',
                'middlename' => 'PILAYRE',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9512570285',
                'birthday' => '2004-07-10',
                'qualifier_id' => 102,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'email' => 'izzavill0116@gmail.com',
                'firstname' => 'IZZA',
                'lastname' => 'VILLAGANAS',
                'middlename' => 'SUMAMPONG',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9616261314',
                'birthday' => '2005-01-16',
                'qualifier_id' => 103,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'email' => 'chavezterence@gmail.com',
                'firstname' => 'TERENCE ANDRÉ',
                'lastname' => 'CHAVEZ',
                'middlename' => 'GARCIA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9279382103',
                'birthday' => '2004-04-22',
                'qualifier_id' => 104,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'email' => 'lyzabellcolcol815ws@gmail.com',
                'firstname' => 'LYZABELL',
                'lastname' => 'COLCOL',
                'middlename' => 'BRAQUEZ',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9187269471',
                'birthday' => '2004-08-15',
                'qualifier_id' => 105,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'email' => 'harriedyolf@gmail.com',
                'firstname' => 'HARRIE FLOYD',
                'lastname' => 'LELIS',
                'middlename' => 'CAMPOREDONDO',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9277345092',
                'birthday' => '2004-12-14',
                'qualifier_id' => 106,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'email' => 'bridgetfernandez19@gmail.com',
                'firstname' => 'MARIA BRIDGET',
                'lastname' => 'FERNANDEZ',
                'middlename' => 'LACASTESANTOS',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9663717107',
                'birthday' => '2005-02-19',
                'qualifier_id' => 107,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'email' => 'ordinario.xandrae@gmail.com',
                'firstname' => 'XANDRAE ERIK',
                'lastname' => 'ORDINARIO',
                'middlename' => 'ABAD',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9300839222',
                'birthday' => '2005-07-08',
                'qualifier_id' => 108,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'email' => 'harveycharlex@gmail.com',
                'firstname' => 'HARVEY CHARLES',
                'lastname' => 'MAGSAYO',
                'middlename' => 'CAINDUG',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9517478230',
                'birthday' => '2004-06-25',
                'qualifier_id' => 109,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'email' => 'geromojohann@gmail.com',
                'firstname' => 'JOHANN SEBASTIAN',
                'lastname' => 'GEROMO',
                'middlename' => 'YOSOYA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9381119240',
                'birthday' => '2005-06-21',
                'qualifier_id' => 110,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'email' => 'fernandezmaverick4@gmail.com',
                'firstname' => 'MAVERICK JANN',
                'lastname' => 'FERNANDEZ',
                'middlename' => 'HERMOSISIMA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9458660672',
                'birthday' => '2003-12-29',
                'qualifier_id' => 111,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'email' => 'renseebanez@gmail.com',
                'firstname' => 'RENSEE LOUIE',
                'lastname' => 'YBAÑEZ',
                'middlename' => 'GUEVARRA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9464764069',
                'birthday' => '2004-09-20',
                'qualifier_id' => 112,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'email' => 'maningatzirah@gmail.com',
                'firstname' => 'ZIRAH',
                'lastname' => 'MANINGAT',
                'middlename' => 'MAGTUBA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9364606954',
                'birthday' => '2004-07-23',
                'qualifier_id' => 113,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'email' => 'velascokaterachel@gmail.com',
                'firstname' => 'KATE RACHEL',
                'lastname' => 'VELASCO',
                'middlename' => 'BELLENO',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9398932043',
                'birthday' => '2005-07-05',
                'qualifier_id' => 114,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'email' => 'kaycylejoyrustique@gmail.com',
                'firstname' => 'KAYCYLE JOY',
                'lastname' => 'RUSTIQUE',
                'middlename' => 'BARROCAMO',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9501208190',
                'birthday' => '2004-10-30',
                'qualifier_id' => 115,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'email' => 'micokleinldelosreyes@gmail.com',
                'firstname' => 'MICO KLEIN',
                'lastname' => 'DELOS REYES',
                'middlename' => 'LIM',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9925030710',
                'birthday' => '2004-12-14',
                'qualifier_id' => 116,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'email' => 'nobnoj20@gmail.com',
                'firstname' => 'JON ANTONEE',
                'lastname' => 'ORILLINEDA',
                'middlename' => 'ACORIN',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9561390937',
                'birthday' => '2004-07-17',
                'qualifier_id' => 117,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'email' => 'drebbalaod24@gmail.com',
                'firstname' => 'DREB BRYAN',
                'lastname' => 'BALAOD',
                'middlename' => 'RELACION',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9566891307',
                'birthday' => '2004-12-02',
                'qualifier_id' => 118,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'email' => 'singidaschrisdeo@gmail.com',
                'firstname' => 'CHRIS DEO',
                'lastname' => 'SINGIDAS',
                'middlename' => 'MALIGAYA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9776605332',
                'birthday' => '2004-11-05',
                'qualifier_id' => 119,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'email' => 'nianee.patangan@gmail.com',
                'firstname' => 'NIANEE MARIE',
                'lastname' => 'PATANGAN',
                'middlename' => 'MABILOG',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9565910126',
                'birthday' => '2004-11-15',
                'qualifier_id' => 120,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'email' => 'vinceridwan.gumbahali@one.uz.edu.ph',
                'firstname' => 'VINCE RIDWAN',
                'lastname' => 'GUMBAHALI',
                'middlename' => 'LACASTESANTOS',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9610312822',
                'birthday' => '2004-09-14',
                'qualifier_id' => 121,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'email' => 'castillotimothykiel@gmail.com',
                'firstname' => 'TIMOTHY KIEL',
                'lastname' => 'CASTILLO',
                'middlename' => 'CABATO',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9092607564',
                'birthday' => '2005-03-30',
                'qualifier_id' => 122,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'email' => 'mhedenblesss.gemmanzo@gmail.com',
                'firstname' => 'MHEDENBLESS GEM',
                'lastname' => 'MANZO',
                'middlename' => 'SALOMON',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9655939499',
                'birthday' => '2004-07-10',
                'qualifier_id' => 123,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'email' => 'singco.karylle@gmail.com',
                'firstname' => 'KARYLLE',
                'lastname' => 'SINGCO',
                'middlename' => 'TOLIN',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9810907868',
                'birthday' => '2004-11-05',
                'qualifier_id' => 124,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'email' => 'whaineperocho032005@gmail.com',
                'firstname' => 'WHAINE KRYSTHIAN',
                'lastname' => 'PEROCHO',
                'middlename' => 'CHUA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9956658320',
                'birthday' => '2005-03-20',
                'qualifier_id' => 125,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'email' => 'arzj570@gmail.com',
                'firstname' => 'ZAMANTHA JUANNE',
                'lastname' => 'SAMSON',
                'middlename' => 'REGENCIA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9700388184',
                'birthday' => '2004-05-06',
                'qualifier_id' => 126,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'email' => 'mmtobillo@gmail.com',
                'firstname' => 'MARKKO LORENZO',
                'lastname' => 'TOBILLO',
                'middlename' => 'MANANGAN',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9052789466',
                'birthday' => '2004-06-08',
                'qualifier_id' => 127,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'email' => 'therealalphavet@gmail.com',
                'firstname' => 'AHMED JOHNNY-FEIGEDHAR',
                'lastname' => 'ALPHA',
                'middlename' => 'KALINGGALAN',
                'suffix' => 'III',
                'sex' => 'M',
                'contact_no' => '9656135103',
                'birthday' => '2004-12-02',
                'qualifier_id' => 128,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'email' => 'akeezia.carreon@gmail.com',
                'firstname' => 'AKEEZIA FIA',
                'lastname' => 'CARREON',
                'middlename' => 'ARQUIZA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9173039952',
                'birthday' => '2005-04-25',
                'qualifier_id' => 129,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'email' => 'hasimshariffkhalifa@gmail.com',
                'firstname' => 'SHARIFF KHALIFA',
                'lastname' => 'HASIM',
                'middlename' => 'ISMAEL',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9817061022',
                'birthday' => '2005-06-08',
                'qualifier_id' => 130,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'email' => 'toribiovincejoriz@gmail.com',
                'firstname' => 'VINCE JORIZ',
                'lastname' => 'TORIBIO',
                'middlename' => 'SANTILLAN',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9361016164',
                'birthday' => '2005-06-19',
                'qualifier_id' => 131,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'email' => 'tubilmarc@gmail.com',
                'firstname' => 'MARC LORIENCE',
                'lastname' => 'TUBIL',
                'middlename' => 'ITEM',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9919350594',
                'birthday' => '2004-12-14',
                'qualifier_id' => 132,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'email' => 'arabellacarylv@gmail.com',
                'firstname' => 'ARABELLA CARYL',
                'lastname' => 'VILLAREAL',
                'middlename' => 'TOLIN',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9129489027',
                'birthday' => '2005-03-08',
                'qualifier_id' => 133,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'email' => 'kylebensali2005@gmail.com',
                'firstname' => 'KYLE EDRIAN',
                'lastname' => 'BENSALI',
                'middlename' => 'LAJA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9565415284',
                'birthday' => '2005-01-12',
                'qualifier_id' => 134,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'email' => 'abloylopez@gmail.com',
                'firstname' => 'JACOB',
                'lastname' => 'LOPEZ',
                'middlename' => 'ENCARNACION',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9491058917',
                'birthday' => '2004-10-28',
                'qualifier_id' => 135,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'email' => 'r.andreada@gmail.com',
                'firstname' => 'REEDHA ANDREADA',
                'lastname' => 'JULJANI',
                'middlename' => 'DAMAHAN',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9610323589',
                'birthday' => '2004-10-08',
                'qualifier_id' => 136,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'email' => 'princeslumawas@gmail.com',
                'firstname' => 'PRINCES NEL ANN',
                'lastname' => 'LUMAWAS',
                'middlename' => 'CALUNOD',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9673657869',
                'birthday' => '2005-06-29',
                'qualifier_id' => 137,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'email' => 'pancho.venn@gmail.com',
                'firstname' => 'CRISTELLE VEN',
                'lastname' => 'PANCHO',
                'middlename' => 'SIPIN',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9517918888',
                'birthday' => '2005-07-27',
                'qualifier_id' => 138,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'email' => 'zveunpoloyapoy@gmail.com',
                'firstname' => 'ZAMANNTHA VEAUNNE',
                'lastname' => 'POLOYAPOY',
                'middlename' => 'CEPE',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9177738167',
                'birthday' => '2004-06-04',
                'qualifier_id' => 139,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'email' => 'quijhanns.lumacad@gmail.com',
                'firstname' => 'QUIJ HANNS',
                'lastname' => 'LUMACAD',
                'middlename' => 'MALMIS',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9505914819',
                'birthday' => '2004-11-22',
                'qualifier_id' => 140,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'email' => 'jaschaisaac.pangandian@g.msuiit.edu.ph',
                'firstname' => 'JASCHA ISAAC',
                'lastname' => 'PANGANDIAN',
                'middlename' => 'BARBARONA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9317182819',
                'birthday' => '2004-10-04',
                'qualifier_id' => 141,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'email' => 'marcmutya318@gmail.com',
                'firstname' => 'MARC EDCIL',
                'lastname' => 'MUTYA',
                'middlename' => 'CRUZ',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9178975401',
                'birthday' => '2005-03-18',
                'qualifier_id' => 142,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'email' => 'razeaceshiongozon@gmail.com',
                'firstname' => 'VINCENT',
                'lastname' => 'SIODORA',
                'middlename' => 'BAYOTAS',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9810659071',
                'birthday' => '2004-11-07',
                'qualifier_id' => 143,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'email' => 'jullianalee13@gmail.com',
                'firstname' => 'JULLIANA DELPHINE',
                'lastname' => 'LEE',
                'middlename' => 'CORTES',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9152276603',
                'birthday' => '2004-08-25',
                'qualifier_id' => 144,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'email' => 'ajalil@zrc.pshs.edu.ph',
                'firstname' => 'ABDUL-MUJER',
                'lastname' => 'JALIL',
                'middlename' => 'CAMLIAN',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9368029877',
                'birthday' => '2005-03-22',
                'qualifier_id' => 145,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'email' => 'almeqdhadjocutan@gmail.com',
                'firstname' => 'AL MEQDHAD IBRAHIM',
                'lastname' => 'JOCUTAN',
                'middlename' => 'BRAZA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9554501035',
                'birthday' => '2005-02-20',
                'qualifier_id' => 146,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            146 => 
            array (
                'id' => 147,
                'email' => 'iannarucas@gmail.com',
                'firstname' => 'IANNA VERONICA',
                'lastname' => 'RUCAS',
                'middlename' => 'CASINTAHAN',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => NULL,
                'birthday' => '2005-11-19',
                'qualifier_id' => 147,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            147 => 
            array (
                'id' => 148,
                'email' => 'kylajremigio@gmail.com',
                'firstname' => 'KYLA JOCEL',
                'lastname' => 'REMIGIO',
                'middlename' => 'AT-AT',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9918236436',
                'birthday' => '2005-07-25',
                'qualifier_id' => 148,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            148 => 
            array (
                'id' => 149,
                'email' => 'bordiosjanmel@gmail.com',
                'firstname' => 'JANMEL',
                'lastname' => 'BORDIOS',
                'middlename' => 'QUERING',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9383276178',
                'birthday' => '2004-04-23',
                'qualifier_id' => 149,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            149 => 
            array (
                'id' => 150,
                'email' => 'seanaugustus09@gmail.com',
                'firstname' => 'SEAN AUGUSTUS',
                'lastname' => 'BAJAO',
                'middlename' => 'DOROT',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9098320455',
                'birthday' => '2004-08-06',
                'qualifier_id' => 150,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            150 => 
            array (
                'id' => 151,
                'email' => 'louise.kayeee@gmail.com',
                'firstname' => 'JONA LOUISE',
                'lastname' => 'VALDEHUEZA',
                'middlename' => 'ELOPRE',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9989517471',
                'birthday' => '2004-09-26',
                'qualifier_id' => 151,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            151 => 
            array (
                'id' => 152,
                'email' => 'shaima.zambo@gmail.com',
                'firstname' => 'SHAIMA',
                'lastname' => 'MARAH',
                'middlename' => 'KARIL',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9567388504',
                'birthday' => '2004-11-19',
                'qualifier_id' => 152,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            152 => 
            array (
                'id' => 153,
                'email' => 'liaa.sgl@gmail.com',
                'firstname' => 'ALIA',
                'lastname' => 'GADJALI',
                'middlename' => 'SADJAIL',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9569269207',
                'birthday' => '2004-11-15',
                'qualifier_id' => 153,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            153 => 
            array (
                'id' => 154,
                'email' => 'aprincessrean@gmail.com',
                'firstname' => 'PRINCESS  REAN MAE',
                'lastname' => 'ANDO',
                'middlename' => 'REQUILLO',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9166521243',
                'birthday' => '2005-05-06',
                'qualifier_id' => 154,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            154 => 
            array (
                'id' => 155,
                'email' => 'anhelmariealabata@gmail.com',
                'firstname' => 'ANGEL MARIE',
                'lastname' => 'ALABATA',
                'middlename' => 'RUBIA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9752771135',
                'birthday' => '2005-07-21',
                'qualifier_id' => 155,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            155 => 
            array (
                'id' => 156,
                'email' => 'arne.xe54@gmail.com',
                'firstname' => 'ARNE CHRISTIAN JOHN',
                'lastname' => 'SENON',
                'middlename' => 'DELA PEÑA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9654018892',
                'birthday' => '2005-12-06',
                'qualifier_id' => 156,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            156 => 
            array (
                'id' => 157,
                'email' => 'ms.jasmineungab@gmail.com',
                'firstname' => 'JASMINE MARIE',
                'lastname' => 'UNGAB',
                'middlename' => 'MACALISAN',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9060769830',
                'birthday' => '2005-10-01',
                'qualifier_id' => 157,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            157 => 
            array (
                'id' => 158,
                'email' => 'johnadorniga@gmail.com',
                'firstname' => 'JOHN RYAN',
                'lastname' => 'ADORNIGA',
                'middlename' => 'BONTIA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9655935559',
                'birthday' => '2005-10-17',
                'qualifier_id' => 158,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            158 => 
            array (
                'id' => 159,
                'email' => 'mishmalun@gmail.com',
                'firstname' => 'MISHAL',
                'lastname' => 'MALUN',
                'middlename' => 'SEJERA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9214002016',
                'birthday' => '2004-11-16',
                'qualifier_id' => 159,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            159 => 
            array (
                'id' => 160,
                'email' => 'krizlejoyc@gmail.com',
                'firstname' => 'KRIZLE JOY',
                'lastname' => 'CORPUZ',
                'middlename' => 'BAUTISTA',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9383065164',
                'birthday' => '2004-12-15',
                'qualifier_id' => 160,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            160 => 
            array (
                'id' => 161,
                'email' => 'mejoradahazelann@gmail.com',
                'firstname' => 'HAZEL ANN',
                'lastname' => 'MEJORADA',
                'middlename' => 'CLARION',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9168489705',
                'birthday' => '2005-06-13',
                'qualifier_id' => 161,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            161 => 
            array (
                'id' => 162,
                'email' => 'jamesmarkescorial@gmail.com',
                'firstname' => 'JAMES MARK',
                'lastname' => 'ESCORIAL',
                'middlename' => 'URSABIA',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9380259746',
                'birthday' => '2004-08-24',
                'qualifier_id' => 162,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            162 => 
            array (
                'id' => 163,
                'email' => 'asianthyjeannin@gmail.com',
                'firstname' => 'ASIANTHY JEANNIN',
                'lastname' => 'SANTILLAN',
                'middlename' => 'ANDICO',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9558120347',
                'birthday' => '2004-08-20',
                'qualifier_id' => 163,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            163 => 
            array (
                'id' => 164,
                'email' => 'anarizageorgina28@gmail.com',
                'firstname' => 'ANARIZA GEORGINA',
                'lastname' => 'MEJORADA',
                'middlename' => 'FORTICH',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9289419898',
                'birthday' => '2005-02-28',
                'qualifier_id' => 164,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            164 => 
            array (
                'id' => 165,
                'email' => 'shinianituda@gmail.com',
                'firstname' => 'SHINIA MIKAELA',
                'lastname' => 'NITUDA',
                'middlename' => 'M',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9816259193',
                'birthday' => '2005-02-28',
                'qualifier_id' => 165,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            165 => 
            array (
                'id' => 166,
                'email' => 'aranaschristianjade@gmail.com',
                'firstname' => 'CHRISTIAN JADE',
                'lastname' => 'ARANAS',
                'middlename' => 'D',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9467626966',
                'birthday' => '2005-02-28',
                'qualifier_id' => 166,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}