<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ScholarEducationTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('scholar_education')->delete();
        
        \DB::table('scholar_education')->insert(array (
            0 => 
            array (
                'id' => 1,
                'school_id' => 310,
                'course_id' => 42,
                'level_id' => 26,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 1,
                'created_at' => '2024-02-05 11:04:06',
                'updated_at' => '2024-02-05 11:04:06',
            ),
            1 => 
            array (
                'id' => 2,
                'school_id' => 310,
                'course_id' => 109,
                'level_id' => 26,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 2,
                'created_at' => '2024-02-05 11:05:35',
                'updated_at' => '2024-02-05 11:05:35',
            ),
            2 => 
            array (
                'id' => 3,
                'school_id' => 310,
                'course_id' => 69,
                'level_id' => 26,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 3,
                'created_at' => '2024-02-05 11:05:53',
                'updated_at' => '2024-02-05 11:05:53',
            ),
            3 => 
            array (
                'id' => 4,
                'school_id' => 310,
                'course_id' => 19,
                'level_id' => 26,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 4,
                'created_at' => '2024-02-05 11:06:20',
                'updated_at' => '2024-02-05 11:06:20',
            ),
            4 => 
            array (
                'id' => 5,
                'school_id' => 310,
                'course_id' => 51,
                'level_id' => 26,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 5,
                'created_at' => '2024-02-05 11:06:54',
                'updated_at' => '2024-02-05 11:06:54',
            ),
            5 => 
            array (
                'id' => 6,
                'school_id' => 285,
                'course_id' => 47,
                'level_id' => 26,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 6,
                'created_at' => '2024-02-05 11:07:32',
                'updated_at' => '2024-02-05 11:07:32',
            ),
            6 => 
            array (
                'id' => 7,
                'school_id' => 310,
                'course_id' => 42,
                'level_id' => 26,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 7,
                'created_at' => '2024-02-05 11:07:51',
                'updated_at' => '2024-02-05 11:07:51',
            ),
            7 => 
            array (
                'id' => 8,
                'school_id' => 310,
                'course_id' => 36,
                'level_id' => 26,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 8,
                'created_at' => '2024-02-05 11:08:12',
                'updated_at' => '2024-02-05 11:08:12',
            ),
            8 => 
            array (
                'id' => 9,
                'school_id' => 310,
                'course_id' => 36,
                'level_id' => 26,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 9,
                'created_at' => '2024-02-05 11:08:48',
                'updated_at' => '2024-02-05 11:08:48',
            ),
            9 => 
            array (
                'id' => 10,
                'school_id' => 310,
                'course_id' => 109,
                'level_id' => 26,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 10,
                'created_at' => '2024-02-05 11:09:17',
                'updated_at' => '2024-02-05 11:09:17',
            ),
            10 => 
            array (
                'id' => 11,
                'school_id' => 277,
                'course_id' => 47,
                'level_id' => 26,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 11,
                'created_at' => '2024-02-05 11:09:44',
                'updated_at' => '2024-02-05 11:09:44',
            ),
            11 => 
            array (
                'id' => 12,
                'school_id' => 310,
                'course_id' => 42,
                'level_id' => 26,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 12,
                'created_at' => '2024-02-05 11:10:05',
                'updated_at' => '2024-02-05 11:10:05',
            ),
            12 => 
            array (
                'id' => 13,
                'school_id' => 310,
                'course_id' => 57,
                'level_id' => 26,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 13,
                'created_at' => '2024-02-05 11:10:32',
                'updated_at' => '2024-02-05 11:10:32',
            ),
            13 => 
            array (
                'id' => 14,
                'school_id' => 310,
                'course_id' => 89,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 14,
                'created_at' => '2024-02-05 11:11:47',
                'updated_at' => '2024-02-05 11:11:47',
            ),
            14 => 
            array (
                'id' => 15,
                'school_id' => 285,
                'course_id' => 109,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 15,
                'created_at' => '2024-02-05 11:12:15',
                'updated_at' => '2024-02-05 11:12:15',
            ),
            15 => 
            array (
                'id' => 16,
                'school_id' => 310,
                'course_id' => 55,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 16,
                'created_at' => '2024-02-05 11:12:52',
                'updated_at' => '2024-02-05 11:12:52',
            ),
            16 => 
            array (
                'id' => 17,
                'school_id' => 310,
                'course_id' => 248,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 17,
                'created_at' => '2024-02-05 11:13:49',
                'updated_at' => '2024-02-05 11:13:49',
            ),
            17 => 
            array (
                'id' => 18,
                'school_id' => 310,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 18,
                'created_at' => '2024-02-05 11:14:09',
                'updated_at' => '2024-02-05 11:14:09',
            ),
            18 => 
            array (
                'id' => 19,
                'school_id' => 310,
                'course_id' => 92,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 19,
                'created_at' => '2024-02-05 11:14:47',
                'updated_at' => '2024-02-05 11:14:47',
            ),
            19 => 
            array (
                'id' => 20,
                'school_id' => 310,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 20,
                'created_at' => '2024-02-05 11:15:07',
                'updated_at' => '2024-02-05 11:15:07',
            ),
            20 => 
            array (
                'id' => 21,
                'school_id' => 277,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 21,
                'created_at' => '2024-02-05 11:15:39',
                'updated_at' => '2024-02-05 11:15:39',
            ),
            21 => 
            array (
                'id' => 22,
                'school_id' => 310,
                'course_id' => 56,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 22,
                'created_at' => '2024-02-05 11:16:01',
                'updated_at' => '2024-02-05 11:16:01',
            ),
            22 => 
            array (
                'id' => 23,
                'school_id' => 310,
                'course_id' => 109,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 23,
                'created_at' => '2024-02-05 11:16:24',
                'updated_at' => '2024-02-05 11:16:24',
            ),
            23 => 
            array (
                'id' => 24,
                'school_id' => 310,
                'course_id' => 109,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 24,
                'created_at' => '2024-02-05 11:16:35',
                'updated_at' => '2024-02-05 11:16:35',
            ),
            24 => 
            array (
                'id' => 25,
                'school_id' => 310,
                'course_id' => 109,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 25,
                'created_at' => '2024-02-05 11:16:56',
                'updated_at' => '2024-02-05 11:16:56',
            ),
            25 => 
            array (
                'id' => 26,
                'school_id' => 310,
                'course_id' => 92,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 26,
                'created_at' => '2024-02-05 11:17:40',
                'updated_at' => '2024-02-05 11:17:40',
            ),
            26 => 
            array (
                'id' => 27,
                'school_id' => 272,
                'course_id' => 77,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 27,
                'created_at' => '2024-02-05 11:19:57',
                'updated_at' => '2024-02-05 11:19:57',
            ),
            27 => 
            array (
                'id' => 28,
                'school_id' => 285,
                'course_id' => 41,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 28,
                'created_at' => '2024-02-05 11:20:24',
                'updated_at' => '2024-02-05 11:20:24',
            ),
            28 => 
            array (
                'id' => 29,
                'school_id' => 310,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 29,
                'created_at' => '2024-02-05 11:20:47',
                'updated_at' => '2024-02-05 11:20:47',
            ),
            29 => 
            array (
                'id' => 30,
                'school_id' => 310,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 30,
                'created_at' => '2024-02-05 11:21:13',
                'updated_at' => '2024-02-05 11:21:13',
            ),
            30 => 
            array (
                'id' => 31,
                'school_id' => 310,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 31,
                'created_at' => '2024-02-05 11:21:57',
                'updated_at' => '2024-02-05 11:21:57',
            ),
            31 => 
            array (
                'id' => 32,
                'school_id' => 310,
                'course_id' => 248,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 32,
                'created_at' => '2024-02-05 11:22:23',
                'updated_at' => '2024-02-05 11:22:23',
            ),
            32 => 
            array (
                'id' => 33,
                'school_id' => 285,
                'course_id' => 41,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 33,
                'created_at' => '2024-02-05 11:22:51',
                'updated_at' => '2024-02-05 11:22:51',
            ),
            33 => 
            array (
                'id' => 34,
                'school_id' => 310,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 34,
                'created_at' => '2024-02-05 11:23:27',
                'updated_at' => '2024-02-05 11:23:27',
            ),
            34 => 
            array (
                'id' => 35,
                'school_id' => 310,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 35,
                'created_at' => '2024-02-05 11:24:29',
                'updated_at' => '2024-02-05 11:24:29',
            ),
            35 => 
            array (
                'id' => 36,
                'school_id' => 310,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 36,
                'created_at' => '2024-02-05 11:24:59',
                'updated_at' => '2024-02-05 11:24:59',
            ),
            36 => 
            array (
                'id' => 37,
                'school_id' => 310,
                'course_id' => 92,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 37,
                'created_at' => '2024-02-05 11:25:23',
                'updated_at' => '2024-02-05 11:25:23',
            ),
            37 => 
            array (
                'id' => 38,
                'school_id' => 310,
                'course_id' => 50,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 38,
                'created_at' => '2024-02-05 11:25:49',
                'updated_at' => '2024-02-05 11:25:49',
            ),
            38 => 
            array (
                'id' => 39,
                'school_id' => 310,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 39,
                'created_at' => '2024-02-05 11:26:11',
                'updated_at' => '2024-02-05 11:26:11',
            ),
            39 => 
            array (
                'id' => 40,
                'school_id' => 285,
                'course_id' => 19,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 40,
                'created_at' => '2024-02-05 11:26:41',
                'updated_at' => '2024-02-05 11:26:41',
            ),
            40 => 
            array (
                'id' => 41,
                'school_id' => 285,
                'course_id' => 111,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 41,
                'created_at' => '2024-02-05 11:27:34',
                'updated_at' => '2024-02-05 11:27:34',
            ),
            41 => 
            array (
                'id' => 42,
                'school_id' => 310,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 42,
                'created_at' => '2024-02-05 11:27:51',
                'updated_at' => '2024-02-05 11:27:51',
            ),
            42 => 
            array (
                'id' => 43,
                'school_id' => 310,
                'course_id' => 248,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 43,
                'created_at' => '2024-02-05 11:28:13',
                'updated_at' => '2024-02-05 11:28:13',
            ),
            43 => 
            array (
                'id' => 44,
                'school_id' => 310,
                'course_id' => 248,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 44,
                'created_at' => '2024-02-05 11:28:36',
                'updated_at' => '2024-02-05 11:28:36',
            ),
            44 => 
            array (
                'id' => 45,
                'school_id' => 310,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 45,
                'created_at' => '2024-02-05 11:28:54',
                'updated_at' => '2024-02-05 11:28:54',
            ),
            45 => 
            array (
                'id' => 46,
                'school_id' => 310,
                'course_id' => 42,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 46,
                'created_at' => '2024-02-05 11:29:12',
                'updated_at' => '2024-02-05 11:29:12',
            ),
            46 => 
            array (
                'id' => 47,
                'school_id' => 310,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 47,
                'created_at' => '2024-02-05 11:29:30',
                'updated_at' => '2024-02-05 11:29:30',
            ),
            47 => 
            array (
                'id' => 48,
                'school_id' => 310,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 48,
                'created_at' => '2024-02-05 11:29:51',
                'updated_at' => '2024-02-05 11:29:51',
            ),
            48 => 
            array (
                'id' => 49,
                'school_id' => 310,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 49,
                'created_at' => '2024-02-05 11:30:07',
                'updated_at' => '2024-02-05 11:30:07',
            ),
            49 => 
            array (
                'id' => 50,
                'school_id' => 310,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 50,
                'created_at' => '2024-02-05 11:30:24',
                'updated_at' => '2024-02-05 11:30:24',
            ),
            50 => 
            array (
                'id' => 51,
                'school_id' => 310,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 51,
                'created_at' => '2024-02-05 11:30:55',
                'updated_at' => '2024-02-05 11:30:55',
            ),
            51 => 
            array (
                'id' => 52,
                'school_id' => 310,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 52,
                'created_at' => '2024-02-05 11:31:18',
                'updated_at' => '2024-02-05 11:31:18',
            ),
            52 => 
            array (
                'id' => 53,
                'school_id' => 310,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 53,
                'created_at' => '2024-02-05 11:31:36',
                'updated_at' => '2024-02-05 11:31:36',
            ),
            53 => 
            array (
                'id' => 54,
                'school_id' => 285,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 54,
                'created_at' => '2024-02-05 11:31:57',
                'updated_at' => '2024-02-05 11:31:57',
            ),
            54 => 
            array (
                'id' => 55,
                'school_id' => 92,
                'course_id' => 51,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 55,
                'created_at' => '2024-02-05 11:32:18',
                'updated_at' => '2024-02-05 11:32:18',
            ),
            55 => 
            array (
                'id' => 56,
                'school_id' => 310,
                'course_id' => 55,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 56,
                'created_at' => '2024-02-05 11:32:48',
                'updated_at' => '2024-02-05 11:32:48',
            ),
            56 => 
            array (
                'id' => 57,
                'school_id' => 310,
                'course_id' => 56,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 57,
                'created_at' => '2024-02-05 11:33:04',
                'updated_at' => '2024-02-05 11:33:04',
            ),
            57 => 
            array (
                'id' => 58,
                'school_id' => 310,
                'course_id' => 248,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 58,
                'created_at' => '2024-02-05 11:33:23',
                'updated_at' => '2024-02-05 11:33:23',
            ),
        ));
        
        
    }
}