<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ScholarEducationTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('scholar_education')->delete();
        
        \DB::table('scholar_education')->insert(array (
            0 => 
            array (
                'id' => 1,
                'school_id' => 18,
                'course_id' => 89,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 1,
                'created_at' => '2024-01-09 10:45:47',
                'updated_at' => '2024-01-09 10:45:47',
            ),
            1 => 
            array (
                'id' => 2,
                'school_id' => 12,
                'course_id' => 109,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 2,
                'created_at' => '2024-01-09 10:46:08',
                'updated_at' => '2024-01-09 10:46:08',
            ),
            2 => 
            array (
                'id' => 3,
                'school_id' => 18,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 3,
                'created_at' => '2024-01-09 10:46:36',
                'updated_at' => '2024-01-09 10:46:36',
            ),
            3 => 
            array (
                'id' => 4,
                'school_id' => 7,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 4,
                'created_at' => '2024-01-09 10:47:09',
                'updated_at' => '2024-01-09 10:47:09',
            ),
            4 => 
            array (
                'id' => 5,
                'school_id' => 18,
                'course_id' => 56,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 5,
                'created_at' => '2024-01-09 10:47:34',
                'updated_at' => '2024-01-09 10:47:34',
            ),
            5 => 
            array (
                'id' => 6,
                'school_id' => 18,
                'course_id' => 92,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 6,
                'created_at' => '2024-01-09 10:47:59',
                'updated_at' => '2024-01-09 10:47:59',
            ),
            6 => 
            array (
                'id' => 7,
                'school_id' => 5,
                'course_id' => 77,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 7,
                'created_at' => '2024-01-09 10:48:25',
                'updated_at' => '2024-01-09 10:48:25',
            ),
            7 => 
            array (
                'id' => 8,
                'school_id' => 18,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 8,
                'created_at' => '2024-01-09 10:48:43',
                'updated_at' => '2024-01-09 10:48:43',
            ),
            8 => 
            array (
                'id' => 9,
                'school_id' => 18,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 9,
                'created_at' => '2024-01-09 10:49:01',
                'updated_at' => '2024-01-09 10:49:01',
            ),
            9 => 
            array (
                'id' => 10,
                'school_id' => 18,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 10,
                'created_at' => '2024-01-09 10:49:17',
                'updated_at' => '2024-01-09 10:49:17',
            ),
            10 => 
            array (
                'id' => 11,
                'school_id' => 18,
                'course_id' => 92,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 11,
                'created_at' => '2024-01-09 10:49:35',
                'updated_at' => '2024-01-09 10:49:35',
            ),
            11 => 
            array (
                'id' => 12,
                'school_id' => 18,
                'course_id' => 50,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 12,
                'created_at' => '2024-01-09 10:49:57',
                'updated_at' => '2024-01-09 10:49:57',
            ),
            12 => 
            array (
                'id' => 13,
                'school_id' => 18,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 13,
                'created_at' => '2024-01-09 10:50:17',
                'updated_at' => '2024-01-09 10:50:17',
            ),
            13 => 
            array (
                'id' => 14,
                'school_id' => 18,
                'course_id' => 248,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 14,
                'created_at' => '2024-01-09 10:50:38',
                'updated_at' => '2024-01-09 10:50:38',
            ),
            14 => 
            array (
                'id' => 15,
                'school_id' => 18,
                'course_id' => 248,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 15,
                'created_at' => '2024-01-09 10:50:58',
                'updated_at' => '2024-01-09 10:50:58',
            ),
            15 => 
            array (
                'id' => 16,
                'school_id' => 18,
                'course_id' => 42,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 16,
                'created_at' => '2024-01-09 10:51:11',
                'updated_at' => '2024-01-09 10:51:11',
            ),
            16 => 
            array (
                'id' => 17,
                'school_id' => 18,
                'course_id' => 55,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 17,
                'created_at' => '2024-01-09 10:51:40',
                'updated_at' => '2024-01-09 10:51:40',
            ),
            17 => 
            array (
                'id' => 18,
                'school_id' => 18,
                'course_id' => 248,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 18,
                'created_at' => '2024-01-09 10:51:54',
                'updated_at' => '2024-01-09 10:51:54',
            ),
            18 => 
            array (
                'id' => 19,
                'school_id' => 18,
                'course_id' => 92,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 19,
                'created_at' => '2024-01-09 10:52:16',
                'updated_at' => '2024-01-09 10:52:16',
            ),
            19 => 
            array (
                'id' => 20,
                'school_id' => 18,
                'course_id' => 109,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 20,
                'created_at' => '2024-01-09 10:52:38',
                'updated_at' => '2024-01-09 10:52:38',
            ),
            20 => 
            array (
                'id' => 21,
                'school_id' => 18,
                'course_id' => 109,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 21,
                'created_at' => '2024-01-09 10:52:43',
                'updated_at' => '2024-01-09 10:52:43',
            ),
            21 => 
            array (
                'id' => 22,
                'school_id' => 18,
                'course_id' => 109,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 22,
                'created_at' => '2024-01-09 10:53:06',
                'updated_at' => '2024-01-09 10:53:06',
            ),
            22 => 
            array (
                'id' => 23,
                'school_id' => 18,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 23,
                'created_at' => '2024-01-09 10:53:32',
                'updated_at' => '2024-01-09 10:53:32',
            ),
            23 => 
            array (
                'id' => 24,
                'school_id' => 18,
                'course_id' => 248,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 24,
                'created_at' => '2024-01-09 10:53:55',
                'updated_at' => '2024-01-09 10:53:55',
            ),
            24 => 
            array (
                'id' => 25,
                'school_id' => 18,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 25,
                'created_at' => '2024-01-09 10:54:15',
                'updated_at' => '2024-01-09 10:54:15',
            ),
            25 => 
            array (
                'id' => 26,
                'school_id' => 18,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 26,
                'created_at' => '2024-01-09 10:54:33',
                'updated_at' => '2024-01-09 10:54:33',
            ),
            26 => 
            array (
                'id' => 27,
                'school_id' => 12,
                'course_id' => 41,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 27,
                'created_at' => '2024-01-09 10:55:03',
                'updated_at' => '2024-01-09 10:55:03',
            ),
            27 => 
            array (
                'id' => 28,
                'school_id' => 18,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 28,
                'created_at' => '2024-01-09 10:55:15',
                'updated_at' => '2024-01-09 10:55:15',
            ),
            28 => 
            array (
                'id' => 29,
                'school_id' => 12,
                'course_id' => 41,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 29,
                'created_at' => '2024-01-09 10:55:39',
                'updated_at' => '2024-01-09 10:55:39',
            ),
            29 => 
            array (
                'id' => 30,
                'school_id' => 18,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 30,
                'created_at' => '2024-01-09 10:55:54',
                'updated_at' => '2024-01-09 10:55:54',
            ),
            30 => 
            array (
                'id' => 31,
                'school_id' => 12,
                'course_id' => 19,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 31,
                'created_at' => '2024-01-09 10:56:16',
                'updated_at' => '2024-01-09 10:56:16',
            ),
            31 => 
            array (
                'id' => 32,
                'school_id' => 12,
                'course_id' => 111,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 32,
                'created_at' => '2024-01-09 10:56:31',
                'updated_at' => '2024-01-09 10:56:31',
            ),
            32 => 
            array (
                'id' => 33,
                'school_id' => 18,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 33,
                'created_at' => '2024-01-09 10:56:58',
                'updated_at' => '2024-01-09 10:56:58',
            ),
            33 => 
            array (
                'id' => 34,
                'school_id' => 18,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 34,
                'created_at' => '2024-01-09 10:57:16',
                'updated_at' => '2024-01-09 10:57:16',
            ),
            34 => 
            array (
                'id' => 35,
                'school_id' => 18,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 35,
                'created_at' => '2024-01-09 10:57:29',
                'updated_at' => '2024-01-09 10:57:29',
            ),
            35 => 
            array (
                'id' => 36,
                'school_id' => 18,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 36,
                'created_at' => '2024-01-09 10:57:52',
                'updated_at' => '2024-01-09 10:57:52',
            ),
            36 => 
            array (
                'id' => 37,
                'school_id' => 2,
                'course_id' => 51,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 37,
                'created_at' => '2024-01-09 10:58:17',
                'updated_at' => '2024-01-09 10:58:17',
            ),
            37 => 
            array (
                'id' => 38,
                'school_id' => 18,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 38,
                'created_at' => '2024-01-09 10:58:42',
                'updated_at' => '2024-01-09 10:58:42',
            ),
            38 => 
            array (
                'id' => 39,
                'school_id' => 18,
                'course_id' => 36,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 39,
                'created_at' => '2024-01-09 10:59:08',
                'updated_at' => '2024-01-09 10:59:08',
            ),
            39 => 
            array (
                'id' => 40,
                'school_id' => 18,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 40,
                'created_at' => '2024-01-09 10:59:24',
                'updated_at' => '2024-01-09 10:59:24',
            ),
            40 => 
            array (
                'id' => 41,
                'school_id' => 18,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 41,
                'created_at' => '2024-01-09 10:59:41',
                'updated_at' => '2024-01-09 10:59:41',
            ),
            41 => 
            array (
                'id' => 42,
                'school_id' => 12,
                'course_id' => 47,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 42,
                'created_at' => '2024-01-09 11:00:07',
                'updated_at' => '2024-01-09 11:00:07',
            ),
            42 => 
            array (
                'id' => 43,
                'school_id' => 18,
                'course_id' => 57,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 43,
                'created_at' => '2024-01-09 11:03:00',
                'updated_at' => '2024-01-09 11:03:00',
            ),
            43 => 
            array (
                'id' => 44,
                'school_id' => 18,
                'course_id' => 56,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 44,
                'created_at' => '2024-01-09 11:03:16',
                'updated_at' => '2024-01-09 11:03:16',
            ),
            44 => 
            array (
                'id' => 45,
                'school_id' => 18,
                'course_id' => 248,
                'level_id' => 24,
                'award_id' => NULL,
                'graduated_year' => NULL,
                'information' => '[]',
                'is_enrolled' => 1,
                'is_shiftee' => 0,
                'is_transferee' => 0,
                'is_completed' => 1,
                'scholar_id' => 45,
                'created_at' => '2024-01-09 11:03:38',
                'updated_at' => '2024-01-09 11:03:38',
            ),
        ));
        
        
    }
}