<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SchoolCampusesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('school_campuses')->delete();
        
        \DB::table('school_campuses')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => NULL,
                'oldname' => 'ABRA STATE INSTITUTE OF SCIENCE AND TECHNOLOGY-LAGANGILANG',
                'campus' => 'MAIN',
                'address' => '2802',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 1,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '140110000',
                'province_code' => '140100000',
                'region_code' => '140000000',
                'assigned_region' => '140000000',
                'created_at' => '2024-01-26 14:29:33',
                'updated_at' => '2024-01-26 14:29:33',
            ),
            1 => 
            array (
                'id' => 2,
                'code' => NULL,
                'oldname' => 'ABRA STATE INSTITUTE OF SCIENCE AND TECHNOLOGY-BANGUED',
                'campus' => 'BANGUED',
                'address' => 'SANTIAGO ST.',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 1,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '140101000',
                'province_code' => '140100000',
                'region_code' => '140000000',
                'assigned_region' => '140000000',
                'created_at' => '2024-01-26 14:30:42',
                'updated_at' => '2024-01-26 14:30:42',
            ),
            2 => 
            array (
                'id' => 3,
                'code' => NULL,
                'oldname' => 'ABUYOG COMMUNITY COLLEGE',
                'campus' => 'MAIN',
                'address' => 'GUINTAGBUCAN',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 2,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '083701000',
                'province_code' => '083700000',
                'region_code' => '080000000',
                'assigned_region' => '160000000',
                'created_at' => '2024-01-26 14:35:11',
                'updated_at' => '2024-01-26 14:35:11',
            ),
            3 => 
            array (
                'id' => 4,
                'code' => NULL,
                'oldname' => 'ACES POLYTECHNIC COLLEGE',
                'campus' => 'MAIN',
                'address' => 'TADECO RD.',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 3,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '112315000',
                'province_code' => '112300000',
                'region_code' => '110000000',
                'assigned_region' => '110000000',
                'created_at' => '2024-01-26 14:37:20',
                'updated_at' => '2024-01-26 14:37:20',
            ),
            4 => 
            array (
                'id' => 5,
                'code' => NULL,
                'oldname' => 'ACES TAGUM COLLEGE,INC.',
                'campus' => 'MAIN',
                'address' => 'PUROK PAG-IBIG, BRGY. MANKILAM',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 4,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '112319000',
                'province_code' => '112300000',
                'region_code' => '110000000',
                'assigned_region' => '110000000',
                'created_at' => '2024-01-26 14:41:04',
                'updated_at' => '2024-01-26 14:41:04',
            ),
            5 => 
            array (
                'id' => 6,
                'code' => NULL,
                'oldname' => 'ACLC COLLEGE OF BUKIDNON',
                'campus' => 'BUKIDNON',
                'address' => 'TS BUILDING, 3535 SAYRE HIGHWAY, HAGKOL',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 5,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '101321000',
                'province_code' => '101300000',
                'region_code' => '100000000',
                'assigned_region' => '100000000',
                'created_at' => '2024-01-26 14:47:17',
                'updated_at' => '2024-01-26 14:47:17',
            ),
            6 => 
            array (
                'id' => 7,
                'code' => NULL,
                'oldname' => 'ACLC COLLEGE OF BUTUAN CITY',
                'campus' => 'BUTUAN CITY',
                'address' => '999 J. C. AQUINO AVENUE',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 5,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '160202000',
                'province_code' => '160200000',
                'region_code' => '160000000',
                'assigned_region' => '120000000',
                'created_at' => '2024-01-26 14:48:51',
                'updated_at' => '2024-01-26 14:48:51',
            ),
            7 => 
            array (
                'id' => 8,
                'code' => NULL,
                'oldname' => 'ACLC COLLEGE OF ORMOC',
                'campus' => 'ORMOC',
                'address' => 'LILIA AVENUE, PUROK CHRYSANTHEMUM BRGY. COGONA',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 5,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '083738000',
                'province_code' => '083700000',
                'region_code' => '080000000',
                'assigned_region' => '080000000',
                'created_at' => '2024-01-26 14:50:41',
                'updated_at' => '2024-01-26 14:50:41',
            ),
            8 => 
            array (
                'id' => 9,
                'code' => NULL,
                'oldname' => 'ACLC COLLEGE OF PUERTO PRINCESA',
                'campus' => 'PUERTO PRINCESA',
                'address' => 'NATIONAL HIGHWAY, BRGY. SAN PEDRO',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 5,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '175316000',
                'province_code' => '175300000',
                'region_code' => '170000000',
                'assigned_region' => '170000000',
                'created_at' => '2024-01-26 14:51:39',
                'updated_at' => '2024-01-26 14:51:39',
            ),
            9 => 
            array (
                'id' => 10,
                'code' => NULL,
                'oldname' => 'ACLC COLLEGE OF TACLOBAN',
                'campus' => 'TACLOBAN',
                'address' => 'M.H. DEL PILAR ST.',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 5,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '083747000',
                'province_code' => '083700000',
                'region_code' => '080000000',
                'assigned_region' => '080000000',
                'created_at' => '2024-01-26 14:52:31',
                'updated_at' => '2024-01-26 14:52:31',
            ),
            10 => 
            array (
                'id' => 11,
                'code' => NULL,
                'oldname' => 'ACLC COLLEGE OF TAYTAY',
                'campus' => 'TAYTAY',
                'address' => 'TAYTAY',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 5,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '045813000',
                'province_code' => '045800000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 14:53:26',
                'updated_at' => '2024-01-26 14:53:26',
            ),
            11 => 
            array (
                'id' => 12,
                'code' => NULL,
                'oldname' => 'ACLC COLLEGE OF MANDAUE',
                'campus' => 'MANDAUE',
                'address' => 'NORTHPOINT BUSINESS CENTER, M.C BRIONES ST., MAGUIKAY',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 5,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '072230000',
                'province_code' => '072200000',
                'region_code' => '070000000',
                'assigned_region' => '070000000',
                'created_at' => '2024-01-26 14:55:06',
                'updated_at' => '2024-01-26 14:55:06',
            ),
            12 => 
            array (
                'id' => 13,
                'code' => NULL,
                'oldname' => 'ACSI COLLEGE ILOILO',
                'campus' => 'ILOILO',
                'address' => 'J.M. BASA STREET',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 6,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '063022000',
                'province_code' => '063000000',
                'region_code' => '060000000',
                'assigned_region' => '060000000',
                'created_at' => '2024-01-26 14:58:43',
                'updated_at' => '2024-01-26 14:58:43',
            ),
            13 => 
            array (
                'id' => 14,
                'code' => NULL,
                'oldname' => 'ACTS COMPUTER COLLEGE',
                'campus' => 'MAIN',
                'address' => 'EGK. BUILDING CORNER A. BONIFACIO STREET, PEDRO GUEVARA AVE.',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 7,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '043426000',
                'province_code' => '043400000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 15:01:55',
                'updated_at' => '2024-01-26 15:01:55',
            ),
            14 => 
            array (
                'id' => 15,
                'code' => NULL,
                'oldname' => 'ADAMSON UNIVERSITY',
                'campus' => 'MAIN',
                'address' => '900 SAN MARCELINO ERMITA',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 8,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '133900000',
                'province_code' => '170000000',
                'region_code' => '130000000',
                'assigned_region' => '130000000',
                'created_at' => '2024-01-26 15:04:12',
                'updated_at' => '2024-01-26 15:04:12',
            ),
            15 => 
            array (
                'id' => 16,
                'code' => NULL,
                'oldname' => 'ADIONG MEMORIAL POLYTECHNIC STATE COLLEGE',
                'campus' => 'MAIN',
                'address' => 'N/A',
                'is_main' => 1,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 9,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '153624000',
                'province_code' => '153600000',
                'region_code' => '150000000',
                'assigned_region' => '150000000',
                'created_at' => '2024-01-26 15:06:19',
                'updated_at' => '2024-01-26 15:06:19',
            ),
            16 => 
            array (
                'id' => 17,
                'code' => NULL,
                'oldname' => 'ADVENTIST MEDICAL CENTER COLLEGE',
                'campus' => 'MAIN',
                'address' => 'MILESTONE DRIVE, PINEVILLE ST., SAN MIGUEL',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 10,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '103504000',
                'province_code' => '103500000',
                'region_code' => '100000000',
                'assigned_region' => '100000000',
                'created_at' => '2024-01-26 15:08:31',
                'updated_at' => '2024-01-26 15:08:31',
            ),
            17 => 
            array (
                'id' => 18,
                'code' => NULL,
                'oldname' => 'ADVENTIST UNIVERSITY OF THE PHILIPPINES',
                'campus' => 'MAIN',
                'address' => 'PUTINGKAHOY',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 11,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '042118000',
                'province_code' => '042100000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 15:10:05',
                'updated_at' => '2024-01-26 15:10:05',
            ),
            18 => 
            array (
                'id' => 19,
                'code' => NULL,
                'oldname' => 'AEMILIANUM COLLEGE, INC.',
                'campus' => 'MAIN',
                'address' => 'RIZAL ST., WEST DISTRICT, PIOT',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 12,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '056216000',
                'province_code' => '056200000',
                'region_code' => '050000000',
                'assigned_region' => '050000000',
                'created_at' => '2024-01-26 15:14:06',
                'updated_at' => '2024-01-26 15:14:06',
            ),
            19 => 
            array (
                'id' => 20,
                'code' => NULL,
                'oldname' => 'AGO MEDICAL AND EDUCATIONAL CENTER - BICOL CHRISTIAN COLLEGE OF MEDICINE',
                'campus' => 'MAIN',
                'address' => 'RIZAL ST.',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 13,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '050506000',
                'province_code' => '050500000',
                'region_code' => '050000000',
                'assigned_region' => '050000000',
                'created_at' => '2024-01-26 15:19:34',
                'updated_at' => '2024-01-26 15:19:34',
            ),
            20 => 
            array (
                'id' => 21,
                'code' => NULL,
                'oldname' => 'AGUSAN DEL SUR STATE COLLEGE OF AGRICULTURE AND TECHNOLOGY',
                'campus' => 'MAIN',
                'address' => 'P2, SAN TEODOR',
                'is_main' => 1,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 14,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '160302000',
                'province_code' => '160300000',
                'region_code' => '160000000',
                'assigned_region' => '160000000',
                'created_at' => '2024-01-26 16:02:15',
                'updated_at' => '2024-01-26 16:02:15',
            ),
            21 => 
            array (
                'id' => 22,
                'code' => NULL,
                'oldname' => 'AKLAN CATHOLIC COLLEGE',
                'campus' => 'MAIN',
                'address' => 'ARCHBISHOP GABRIEL M. REYES STREET',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 15,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '060407000',
                'province_code' => '060400000',
                'region_code' => '060000000',
                'assigned_region' => '060000000',
                'created_at' => '2024-01-26 16:04:06',
                'updated_at' => '2024-01-26 16:04:06',
            ),
            22 => 
            array (
                'id' => 23,
                'code' => NULL,
                'oldname' => 'AKLAN POLYTECHNIC COLLEGE',
                'campus' => 'MAIN',
                'address' => 'QUEZON AVENUE',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 16,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '060407000',
                'province_code' => '060400000',
                'region_code' => '060000000',
                'assigned_region' => '060000000',
                'created_at' => '2024-01-26 16:04:58',
                'updated_at' => '2024-01-26 16:04:58',
            ),
            23 => 
            array (
                'id' => 24,
                'code' => NULL,
                'oldname' => 'AKLAN STATE UNIVERSITY-BANGA',
                'campus' => 'BANGA',
                'address' => 'BACAN',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 17,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '060403000',
                'province_code' => '060400000',
                'region_code' => '060000000',
                'assigned_region' => '060000000',
                'created_at' => '2024-01-26 16:08:09',
                'updated_at' => '2024-01-26 16:08:09',
            ),
            24 => 
            array (
                'id' => 25,
                'code' => NULL,
                'oldname' => 'AKLAN STATE UNIVERSITY-IBAJAY',
                'campus' => 'IBAJAY',
                'address' => 'COLONG-COLONG',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 17,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '060406000',
                'province_code' => '060400000',
                'region_code' => '060000000',
                'assigned_region' => '060000000',
                'created_at' => '2024-01-26 16:08:49',
                'updated_at' => '2024-01-26 16:08:49',
            ),
            25 => 
            array (
                'id' => 26,
                'code' => NULL,
                'oldname' => 'AKLAN STATE UNIVERSITY-KALIBO',
                'campus' => 'KALIBO',
                'address' => 'ROXAS AVE. EXT.',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 17,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '060407000',
                'province_code' => '060400000',
                'region_code' => '060000000',
                'assigned_region' => '060000000',
                'created_at' => '2024-01-26 16:09:46',
                'updated_at' => '2024-01-26 16:09:46',
            ),
            26 => 
            array (
                'id' => 27,
                'code' => NULL,
                'oldname' => 'AKLAN STATE UNIVERSITY-NEW WASHINGTON',
                'campus' => 'NEW WASHINGTON',
                'address' => 'POBLACION',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 17,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '060415000',
                'province_code' => '060400000',
                'region_code' => '060000000',
                'assigned_region' => '060000000',
                'created_at' => '2024-01-26 16:10:15',
                'updated_at' => '2024-01-26 16:10:15',
            ),
            27 => 
            array (
                'id' => 28,
                'code' => NULL,
                'oldname' => 'ALDERGATE COLLEGE, INC.',
                'campus' => 'MAIN',
                'address' => 'BRGY. QUIRINO',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 18,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '025013000',
                'province_code' => '025000000',
                'region_code' => '020000000',
                'assigned_region' => '020000000',
                'created_at' => '2024-01-26 16:12:16',
                'updated_at' => '2024-01-26 16:12:16',
            ),
            28 => 
            array (
                'id' => 29,
                'code' => '4100013',
                'oldname' => 'AMA COMPUTER COLLEGE EAST RIZAL BRANCH',
                'campus' => 'EAST RIZAL BRANCH',
                'address' => 'BRGY. MAYAMOT',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '045802000',
                'province_code' => '045800000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            29 => 
            array (
                'id' => 30,
                'code' => '600100',
                'oldname' => 'AMA COMPUTER COLLEGE ILOILO',
                'campus' => 'ILOILO',
                'address' => '',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '063022000',
                'province_code' => '063000000',
                'region_code' => '060000000',
                'assigned_region' => '060000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            30 => 
            array (
                'id' => 31,
                'code' => '100004',
                'oldname' => 'AMA COMPUTER COLLEGE LAOAG CITY INC.',
                'campus' => 'LAOAG CITY INC.',
                'address' => 'BRGY. 17 PACIFIC BLDG., DON E_RUIS',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 5,
                'grading_id' => 9,
                'municipality_code' => '012812000',
                'province_code' => '012800000',
                'region_code' => '010000000',
                'assigned_region' => '010000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            31 => 
            array (
                'id' => 32,
                'code' => '300108',
                'oldname' => 'AMA COMPUTER COLLEGE MALOLOS',
                'campus' => 'MALOLOS',
                'address' => 'SUMAPANG MATANDA MCARTHUR HIWAY',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 5,
                'grading_id' => 9,
                'municipality_code' => '031410000',
                'province_code' => '031400000',
                'region_code' => '030000000',
                'assigned_region' => '030000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            32 => 
            array (
                'id' => 33,
                'code' => '100002',
                'oldname' => 'AMA COMPUTER COLLEGE OF PANGASINAN INC.',
                'campus' => 'PANGASINAN',
                'address' => 'BRGY. SAN MIGUEL',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 5,
                'grading_id' => 9,
                'municipality_code' => '015517000',
                'province_code' => '015500000',
                'region_code' => '010000000',
                'assigned_region' => '010000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            33 => 
            array (
                'id' => 34,
                'code' => '100005',
                'oldname' => 'AMA COMPUTER COLLEGE SAN FERNANDO CITY, LA UNION INC.',
                'campus' => 'SAN FERNANDO CITY',
                'address' => 'BARANGAY II',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 5,
                'grading_id' => 9,
                'municipality_code' => '013314000',
                'province_code' => '013300000',
                'region_code' => '010000000',
                'assigned_region' => '010000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            34 => 
            array (
                'id' => 35,
                'code' => '600006',
                'oldname' => 'AMA COMPUTER COLLEGE-BACOLOD CITY',
                'campus' => 'BACOLOD CITY',
                'address' => 'NORTH DRIVE',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 6,
                'grading_id' => 9,
                'municipality_code' => '064501000',
                'province_code' => '064500000',
                'region_code' => '070000000',
                'assigned_region' => '070000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            35 => 
            array (
                'id' => 36,
                'code' => '4100004',
                'oldname' => 'AMA COMPUTER COLLEGE-BATANGAS CITY',
                'campus' => 'BATANGAS CITY',
                'address' => 'BRGY. BOLBOK, BATANGAS CITYA',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '041005000',
                'province_code' => '041000000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            36 => 
            array (
                'id' => 37,
                'code' => '4100005',
                'oldname' => 'AMA COMPUTER COLLEGE-BIÑAN CITY',
                'campus' => 'BIÑAN CITY',
                'address' => '',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '043403000',
                'province_code' => '043400000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            37 => 
            array (
                'id' => 38,
                'code' => '1000002',
                'oldname' => 'AMA COMPUTER COLLEGE-CAGAYAN DE ORO CITY',
                'campus' => 'CAGAYAN DE ORO CITY',
                'address' => 'JR BORJA-DAUMAR ST., COGON',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '104305000',
                'province_code' => '104300000',
                'region_code' => '100000000',
                'assigned_region' => '100000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            38 => 
            array (
                'id' => 39,
                'code' => '4100006',
                'oldname' => 'AMA COMPUTER COLLEGE-CALAMBA CITY',
                'campus' => 'CALAMBA CITY',
                'address' => 'NATIONAL HIGHWAY, PARIAN',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '043405000',
                'province_code' => '043400000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            39 => 
            array (
                'id' => 40,
                'code' => '4100177',
                'oldname' => 'AMA COMPUTER COLLEGE-CAVITE',
                'campus' => 'CAVITE',
                'address' => 'BICLATAN',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '042108000',
                'province_code' => '042100000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            40 => 
            array (
                'id' => 41,
                'code' => '1100003',
                'oldname' => 'AMA COMPUTER COLLEGE-DAVAO',
                'campus' => 'DAVAO',
                'address' => '',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 5,
                'grading_id' => 9,
                'municipality_code' => '112402000',
                'province_code' => '112400000',
                'region_code' => '110000000',
                'assigned_region' => '110000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            41 => 
            array (
                'id' => 42,
                'code' => '700058',
                'oldname' => 'AMA COMPUTER COLLEGE-DUMAGUETE',
                'campus' => 'DUMAGUETE',
                'address' => '',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 5,
                'grading_id' => 9,
                'municipality_code' => '074610000',
                'province_code' => '074600000',
                'region_code' => '070000000',
                'assigned_region' => '070000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            42 => 
            array (
                'id' => 43,
                'code' => '1600116',
                'oldname' => 'AMA COMPUTER COLLEGE-FAIRVIEW',
                'campus' => 'FAIRVIEW',
                'address' => '',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '137404000',
                'province_code' => '170000000',
                'region_code' => '130000000',
                'assigned_region' => '130000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            43 => 
            array (
                'id' => 44,
                'code' => '1600002',
                'oldname' => 'AMA COMPUTER COLLEGE-LAS PIÑAS CITY',
                'campus' => 'LAS PIÑAS CITY',
                'address' => '',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 5,
                'grading_id' => 9,
                'municipality_code' => '137601000',
                'province_code' => '170000000',
                'region_code' => '130000000',
                'assigned_region' => '130000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            44 => 
            array (
                'id' => 45,
                'code' => '500003',
                'oldname' => 'AMA COMPUTER COLLEGE-LEGAZPI CITY',
                'campus' => 'LEGAZPI CITY',
                'address' => 'RIZAL ST., ALBAY DISTRICT',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '050506000',
                'province_code' => '050500000',
                'region_code' => '050000000',
                'assigned_region' => '050000000',
                'created_at' => '2024-01-26 21:30:15',
                'updated_at' => '2024-01-26 21:30:15',
            ),
            45 => 
            array (
                'id' => 46,
                'code' => '4100007',
                'oldname' => 'AMA COMPUTER COLLEGE-LIPA CITY',
                'campus' => 'LIPA CITY',
                'address' => 'AYALA HI-WAY, BALINTAWAK, LIPA CITY',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '041014000',
                'province_code' => '041000000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 21:30:16',
                'updated_at' => '2024-01-26 21:30:16',
            ),
            46 => 
            array (
                'id' => 47,
                'code' => '1600003',
                'oldname' => 'AMA COMPUTER COLLEGE-MAKATI CITY',
                'campus' => 'MAKATI CITY',
                'address' => 'AMA ONE BLDG., 5486 SOUTH SUPERHIGHWAY COR. GEN. TINIO ST. BANGKAL',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 5,
                'grading_id' => 9,
                'municipality_code' => '137602000',
                'province_code' => '170000000',
                'region_code' => '130000000',
                'assigned_region' => '130000000',
                'created_at' => '2024-01-26 21:30:16',
                'updated_at' => '2024-01-26 21:30:16',
            ),
            47 => 
            array (
                'id' => 48,
                'code' => '1600004',
                'oldname' => 'AMA COMPUTER COLLEGE-MANDALUYONG CITY',
                'campus' => 'MANDALUYONG CITY',
                'address' => 'CALIFORNIA GARDEN SQUARE, DOMINGO M. GUEVARA ST.',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 5,
                'grading_id' => 9,
                'municipality_code' => '137401000',
                'province_code' => '170000000',
                'region_code' => '130000000',
                'assigned_region' => '130000000',
                'created_at' => '2024-01-26 21:30:16',
                'updated_at' => '2024-01-26 21:30:16',
            ),
            48 => 
            array (
                'id' => 49,
                'code' => '1600125',
                'oldname' => 'AMA COMPUTER COLLEGE-PARAÑAQUE',
                'campus' => 'PARAÑAQUE',
                'address' => '8226 SOOKEE BLDG DR. A SANTOS AVE SUCAT',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 5,
                'grading_id' => 9,
                'municipality_code' => '137604000',
                'province_code' => '170000000',
                'region_code' => '130000000',
                'assigned_region' => '130000000',
                'created_at' => '2024-01-26 21:30:16',
                'updated_at' => '2024-01-26 21:30:16',
            ),
            49 => 
            array (
                'id' => 50,
                'code' => '800001',
                'oldname' => 'AMA COMPUTER COLLEGE-TACLOBAN CITY',
                'campus' => 'TACLOBAN CITY',
                'address' => 'NO. 104 AVENIDA VETERANOS, DOWNTOWN',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '083747000',
                'province_code' => '083700000',
                'region_code' => '080000000',
                'assigned_region' => '080000000',
                'created_at' => '2024-01-26 21:30:16',
                'updated_at' => '2024-01-26 21:30:16',
            ),
            50 => 
            array (
                'id' => 51,
                'code' => '300001',
                'oldname' => 'AMA COMPUTER COLLEGE-TARLAC',
                'campus' => 'TARLAC',
                'address' => 'ZAMORA ST.',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 19,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '036916000',
                'province_code' => '036900000',
                'region_code' => '030000000',
                'assigned_region' => '030000000',
                'created_at' => '2024-01-26 21:30:16',
                'updated_at' => '2024-01-26 21:30:16',
            ),
            51 => 
            array (
                'id' => 52,
                'code' => '1100091',
            'oldname' => 'AMA COMPUTER LEARNING CENTER (ACLC)',
                'campus' => 'DAVAO',
                'address' => 'SAN FELIX BLDG., MCARTHUR HIGHWAY, MATINA',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '112402000',
                'province_code' => '112400000',
                'region_code' => '110000000',
                'assigned_region' => '110000000',
                'created_at' => '2024-01-26 22:10:52',
                'updated_at' => '2024-01-26 22:10:52',
            ),
            52 => 
            array (
                'id' => 53,
                'code' => '500004',
            'oldname' => 'AMA COMPUTER LEARNING CENTER (ACLC) OF NAGA CITY INC',
                'campus' => 'NAGA CITY',
                'address' => '4/F NAGA LAND, E. ANGELES ST.',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '051724000',
                'province_code' => '051700000',
                'region_code' => '050000000',
                'assigned_region' => '050000000',
                'created_at' => '2024-01-26 22:10:52',
                'updated_at' => '2024-01-26 22:10:52',
            ),
            53 => 
            array (
                'id' => 54,
                'code' => '1200003',
                'oldname' => 'AMA COMPUTER LEARNING CENTER COLLEGE OF MARBEL',
                'campus' => 'MARBEL',
                'address' => 'GENSAN DRIVE CONER, FRANCISCO ZULUETA ST,',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '126306000',
                'province_code' => '126300000',
                'region_code' => '120000000',
                'assigned_region' => '120000000',
                'created_at' => '2024-01-26 22:10:52',
                'updated_at' => '2024-01-26 22:10:52',
            ),
            54 => 
            array (
                'id' => 55,
                'code' => '4100009',
                'oldname' => 'AMA COMPUTER LEARNING CENTER OF ANTIPOLO, INC.',
                'campus' => 'ANTIPOLO',
                'address' => 'BARANGAY SAN ROQUE POB. ANTIPOLO CITY',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '045802000',
                'province_code' => '045800000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 22:10:52',
                'updated_at' => '2024-01-26 22:10:52',
            ),
            55 => 
            array (
                'id' => 56,
                'code' => '600007',
                'oldname' => 'AMA COMPUTER LEARNING CENTER-AKLAN',
                'campus' => 'AKLAN',
                'address' => 'PASTRANA ST',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '060407000',
                'province_code' => '060400000',
                'region_code' => '060000000',
                'assigned_region' => '060000000',
                'created_at' => '2024-01-26 22:10:52',
                'updated_at' => '2024-01-26 22:10:52',
            ),
            56 => 
            array (
                'id' => 57,
                'code' => '1500003',
                'oldname' => 'AMA COMPUTER LEARNING CENTER-BAGUIO CITY',
                'campus' => 'BAGUIO CITY',
                'address' => 'CAR',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '141102000',
                'province_code' => '141100000',
                'region_code' => '140000000',
                'assigned_region' => '140000000',
                'created_at' => '2024-01-26 22:10:53',
                'updated_at' => '2024-01-26 22:10:53',
            ),
            57 => 
            array (
                'id' => 58,
                'code' => '300002',
                'oldname' => 'AMA COMPUTER LEARNING CENTER-BALANGA',
                'campus' => 'BALANGA',
                'address' => '49 DON MANUEL BANZON AVENUE,',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '030803000',
                'province_code' => '030800000',
                'region_code' => '030000000',
                'assigned_region' => '030000000',
                'created_at' => '2024-01-26 22:10:53',
                'updated_at' => '2024-01-26 22:10:53',
            ),
            58 => 
            array (
                'id' => 59,
                'code' => '1301023',
                'oldname' => 'AMA COMPUTER LEARNING CENTER-BUTUAN',
                'campus' => 'BUTUAN',
                'address' => 'CARAGA',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '160202000',
                'province_code' => '160200000',
                'region_code' => '160000000',
                'assigned_region' => '160000000',
                'created_at' => '2024-01-26 22:10:53',
                'updated_at' => '2024-01-26 22:10:53',
            ),
            59 => 
            array (
                'id' => 60,
                'code' => '4100010',
                'oldname' => 'AMA COMPUTER LEARNING CENTER-CALAMBA CITY',
                'campus' => 'CALAMBA CITY',
                'address' => 'LAGUNA',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '043405000',
                'province_code' => '043400000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 22:10:53',
                'updated_at' => '2024-01-26 22:10:53',
            ),
            60 => 
            array (
                'id' => 61,
                'code' => '500067',
                'oldname' => 'AMA COMPUTER LEARNING CENTER-DAET',
                'campus' => 'DAET',
                'address' => '5',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '051603000',
                'province_code' => '051600000',
                'region_code' => '050000000',
                'assigned_region' => '050000000',
                'created_at' => '2024-01-26 22:10:53',
                'updated_at' => '2024-01-26 22:10:53',
            ),
            61 => 
            array (
                'id' => 62,
                'code' => '600008',
                'oldname' => 'AMA COMPUTER LEARNING CENTER-ILOILO',
                'campus' => 'ILOILO',
                'address' => '22 DELGADO ST',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '063022000',
                'province_code' => '063000000',
                'region_code' => '060000000',
                'assigned_region' => '060000000',
                'created_at' => '2024-01-26 22:10:53',
                'updated_at' => '2024-01-26 22:10:53',
            ),
            62 => 
            array (
                'id' => 63,
                'code' => '4100014',
                'oldname' => 'AMA COMPUTER LEARNING CENTER-LIPA CITY',
                'campus' => 'LIPA CITY',
                'address' => 'CASA BUENA BLDG., P. BURGOS ST.A',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '041014000',
                'province_code' => '041000000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 22:10:53',
                'updated_at' => '2024-01-26 22:10:53',
            ),
            63 => 
            array (
                'id' => 64,
                'code' => '4100015',
                'oldname' => 'AMA COMPUTER LEARNING CENTER-LUCENA CITY',
                'campus' => 'LUCENA CITY',
                'address' => '4A',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '045624000',
                'province_code' => '045600000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 22:10:53',
                'updated_at' => '2024-01-26 22:10:53',
            ),
            64 => 
            array (
                'id' => 65,
                'code' => '4100016',
                'oldname' => 'AMA COMPUTER LEARNING CENTER-ROSARIO',
                'campus' => 'ROSARIO',
                'address' => '4A',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '041021000',
                'province_code' => '041000000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 22:10:53',
                'updated_at' => '2024-01-26 22:10:53',
            ),
            65 => 
            array (
                'id' => 66,
                'code' => '600009',
                'oldname' => 'AMA COMPUTER LEARNING CENTER-ROXAS CITY',
                'campus' => 'ROXAS CITY',
                'address' => '6',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '061914000',
                'province_code' => '061900000',
                'region_code' => '060000000',
                'assigned_region' => '060000000',
                'created_at' => '2024-01-26 22:10:53',
                'updated_at' => '2024-01-26 22:10:53',
            ),
            66 => 
            array (
                'id' => 67,
                'code' => '4100017',
                'oldname' => 'AMA COMPUTER LEARNING CENTER-SAN PABLO CITY',
                'campus' => 'SAN PABLO CITY',
                'address' => 'JAMORA BUILDING',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '043424000',
                'province_code' => '043400000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 22:10:53',
                'updated_at' => '2024-01-26 22:10:53',
            ),
            67 => 
            array (
                'id' => 68,
                'code' => '1100004',
                'oldname' => 'AMA COMPUTER LEARNING CENTER-TAGUM',
                'campus' => 'TAGUM',
                'address' => 'CAP BLDG., PUROK NARRA, VISAYAN VILLAGE',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 20,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '112319000',
                'province_code' => '112300000',
                'region_code' => '110000000',
                'assigned_region' => '110000000',
                'created_at' => '2024-01-26 22:10:53',
                'updated_at' => '2024-01-26 22:10:53',
            ),
            68 => 
            array (
                'id' => 69,
                'code' => NULL,
                'oldname' => 'AMA UNIVERSITY-QUEZON CITY',
                'campus' => 'QUEZON CITY',
                'address' => 'MAXIMA ST. VILLA ARCA SUBD. PROJ. 8',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 21,
                'term_id' => 5,
                'grading_id' => 9,
                'municipality_code' => '137404000',
                'province_code' => '170000000',
                'region_code' => '130000000',
                'assigned_region' => '130000000',
                'created_at' => '2024-01-26 22:16:37',
                'updated_at' => '2024-01-26 22:16:37',
            ),
            69 => 
            array (
                'id' => 70,
                'code' => NULL,
                'oldname' => 'AMA COMPUTER UNIVERSITY-CAVITE',
                'campus' => 'CAVITE',
                'address' => 'LANGKAAN 1 BRIDGE 2, GOVERNOR\'S DRIVE',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 21,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '042106000',
                'province_code' => '042100000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 22:18:38',
                'updated_at' => '2024-01-26 22:18:38',
            ),
            70 => 
            array (
                'id' => 71,
                'code' => NULL,
                'oldname' => 'AMANDO COPE COLLEGE',
                'campus' => 'MAIN',
                'address' => 'A.A. BERCES ST., BARANGHAWON',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 22,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '050517000',
                'province_code' => '050500000',
                'region_code' => '050000000',
                'assigned_region' => '050000000',
                'created_at' => '2024-01-26 22:22:06',
                'updated_at' => '2024-01-26 22:22:06',
            ),
            71 => 
            array (
                'id' => 72,
                'code' => NULL,
                'oldname' => 'ANDRES BONIFACIO COLLEGE',
                'campus' => 'MAIN',
                'address' => 'MIPUTAK',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 23,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097202000',
                'province_code' => '097200000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2024-01-26 22:24:58',
                'updated_at' => '2024-01-26 22:24:58',
            ),
            72 => 
            array (
                'id' => 73,
                'code' => NULL,
                'oldname' => 'ANGELES UNIVERSITY FOUNDATION',
                'campus' => 'MAIN',
                'address' => 'MAC ARTHUR HIGHWAY',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 24,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '035401000',
                'province_code' => '035400000',
                'region_code' => '030000000',
                'assigned_region' => '030000000',
                'created_at' => '2024-01-26 22:26:15',
                'updated_at' => '2024-01-26 22:26:15',
            ),
            73 => 
            array (
                'id' => 74,
                'code' => NULL,
                'oldname' => 'APAYAO STATE COLLEGE',
                'campus' => 'MAIN',
                'address' => 'MALAMA',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 25,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '148102000',
                'province_code' => '148100000',
                'region_code' => '140000000',
                'assigned_region' => '140000000',
                'created_at' => '2024-01-26 22:31:56',
                'updated_at' => '2024-01-26 22:31:56',
            ),
            74 => 
            array (
                'id' => 75,
                'code' => NULL,
                'oldname' => 'APAYAO STATE COLLEGE-LUNA',
                'campus' => 'LUNA',
                'address' => 'SAN ISIDRO SUR',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 25,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '148105000',
                'province_code' => '148100000',
                'region_code' => '140000000',
                'assigned_region' => '140000000',
                'created_at' => '2024-01-26 22:32:44',
                'updated_at' => '2024-01-26 22:32:44',
            ),
            75 => 
            array (
                'id' => 76,
                'code' => NULL,
                'oldname' => 'ARELLANO UNIVERSITY-JUAN SUMULONG',
                'campus' => 'JUAN SUMULONG',
                'address' => '2600 LEGARDA ST., SAMPALOC',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 26,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '133900000',
                'province_code' => '170000000',
                'region_code' => '130000000',
                'assigned_region' => '130000000',
                'created_at' => '2024-01-26 22:35:52',
                'updated_at' => '2024-01-26 22:35:52',
            ),
            76 => 
            array (
                'id' => 77,
                'code' => NULL,
                'oldname' => 'ARELLANO UNIVERSITY-JOSE ABAD SANTOS',
                'campus' => 'JOSE ABAD SANTOS',
                'address' => '3058 TAFT AVENUE, PASAY CITY',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 26,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '137605000',
                'province_code' => '170000000',
                'region_code' => '130000000',
                'assigned_region' => '130000000',
                'created_at' => '2024-01-26 22:36:48',
                'updated_at' => '2024-01-26 22:36:48',
            ),
            77 => 
            array (
                'id' => 78,
                'code' => NULL,
                'oldname' => 'ARRIESGADO COLLEGE FOUNDATION, INC.',
                'campus' => 'MAIN',
                'address' => '201 BONIFACIO ST., MAGUGPO, POBLACION',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 27,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '112319000',
                'province_code' => '112300000',
                'region_code' => '110000000',
                'assigned_region' => '110000000',
                'created_at' => '2024-01-26 22:39:24',
                'updated_at' => '2024-01-26 22:39:24',
            ),
            78 => 
            array (
                'id' => 79,
                'code' => NULL,
                'oldname' => 'ASIA PACIFIC COLLEGE',
                'campus' => 'MAIN',
                'address' => '3 HUMABON PLACE, MAGALLANES',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 28,
                'term_id' => 5,
                'grading_id' => 9,
                'municipality_code' => '137602000',
                'province_code' => '170000000',
                'region_code' => '130000000',
                'assigned_region' => '130000000',
                'created_at' => '2024-01-26 22:41:11',
                'updated_at' => '2024-01-26 22:41:11',
            ),
            79 => 
            array (
                'id' => 80,
                'code' => NULL,
                'oldname' => 'ASIA PACIFIC COLLEGE OF ADVANCE STUDIES',
                'campus' => 'MAIN',
                'address' => 'A.H BANZON ST.',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 29,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '030803000',
                'province_code' => '030800000',
                'region_code' => '030000000',
                'assigned_region' => '030000000',
                'created_at' => '2024-01-26 22:42:20',
                'updated_at' => '2024-01-26 22:42:20',
            ),
            80 => 
            array (
                'id' => 81,
                'code' => NULL,
                'oldname' => 'ASIA TECHNOLOGICAL SCHOOL OF SCIENCE AND ARTS',
                'campus' => 'MAIN',
                'address' => '1506 BRGY. DILA',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 30,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '043428000',
                'province_code' => '043400000',
                'region_code' => '040000000',
                'assigned_region' => '040000000',
                'created_at' => '2024-01-26 22:45:15',
                'updated_at' => '2024-01-26 22:45:15',
            ),
            81 => 
            array (
                'id' => 82,
                'code' => NULL,
                'oldname' => 'ASIAN COLLEGE',
                'campus' => 'QUEZON CITY',
                'address' => '1013 AURO BLVD., PROJ. 3',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 31,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '137404000',
                'province_code' => '170000000',
                'region_code' => '130000000',
                'assigned_region' => '130000000',
                'created_at' => '2024-01-26 22:58:51',
                'updated_at' => '2024-01-26 22:58:51',
            ),
            82 => 
            array (
                'id' => 83,
                'code' => NULL,
                'oldname' => 'ASIAN COLLEGE - DUMAGUETE',
                'campus' => 'DUMAGUETE CITY',
                'address' => 'DR. V. LOCSIN STREET',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 31,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '074610000',
                'province_code' => '074600000',
                'region_code' => '070000000',
                'assigned_region' => '070000000',
                'created_at' => '2024-01-26 22:59:48',
                'updated_at' => '2024-01-26 22:59:48',
            ),
            83 => 
            array (
                'id' => 84,
                'code' => NULL,
                'oldname' => 'ASIAN COLLEGE OF TECHNOLOGY - INTERNATIONAL EDUCATIONAL FOUNDATION',
                'campus' => 'MAIN',
                'address' => 'CORNER LEON KILAT AND P. DEL ROSARIO STREET',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 32,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '072217000',
                'province_code' => '072200000',
                'region_code' => '070000000',
                'assigned_region' => '070000000',
                'created_at' => '2024-01-26 23:01:05',
                'updated_at' => '2024-01-26 23:01:05',
            ),
            84 => 
            array (
                'id' => 85,
                'code' => NULL,
                'oldname' => 'ASIAN COLLEGE FOUNDATION',
                'campus' => 'MAIN',
                'address' => 'ESTIPONA VILLAGE , KM 3 J.C AQUINO AVENUE',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 33,
                'term_id' => 6,
                'grading_id' => 9,
                'municipality_code' => '160202000',
                'province_code' => '160200000',
                'region_code' => '160000000',
                'assigned_region' => '160000000',
                'created_at' => '2024-01-26 23:02:11',
                'updated_at' => '2024-01-26 23:02:11',
            ),
            85 => 
            array (
                'id' => 86,
                'code' => NULL,
                'oldname' => 'ASSUMPTION COLLEGE OF DAVAO',
                'campus' => 'DAVAO',
                'address' => 'J.P. CABAGUIO AVE.',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 34,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '112402000',
                'province_code' => '112400000',
                'region_code' => '110000000',
                'assigned_region' => '110000000',
                'created_at' => '2024-01-26 23:06:12',
                'updated_at' => '2024-01-26 23:06:12',
            ),
            86 => 
            array (
                'id' => 87,
                'code' => NULL,
                'oldname' => 'ASSUMPTION COLLEGE OF NABUNTURAN',
                'campus' => 'NABUNTURAN',
                'address' => 'P-1, ARELLANO STREET, POBLACION',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 34,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '118209000',
                'province_code' => '118200000',
                'region_code' => '110000000',
                'assigned_region' => '110000000',
                'created_at' => '2024-01-26 23:06:52',
                'updated_at' => '2024-01-26 23:06:52',
            ),
            87 => 
            array (
                'id' => 88,
                'code' => NULL,
                'oldname' => 'ASYNCHRONOUS SYSTEMS AND COMPUTER INFORMATION INSTITUTE',
                'campus' => 'MAIN',
                'address' => 'NA',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 35,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '030803000',
                'province_code' => '030800000',
                'region_code' => '030000000',
                'assigned_region' => '030000000',
                'created_at' => '2024-01-26 23:09:49',
                'updated_at' => '2024-01-26 23:09:49',
            ),
            88 => 
            array (
                'id' => 89,
                'code' => NULL,
                'oldname' => 'ATENEO DE DAVAO UNIVERSITY',
                'campus' => 'MAIN',
                'address' => 'E. JACINTO STREET',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 36,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '112402000',
                'province_code' => '112400000',
                'region_code' => '110000000',
                'assigned_region' => '110000000',
                'created_at' => '2024-01-26 23:13:33',
                'updated_at' => '2024-01-26 23:13:33',
            ),
            89 => 
            array (
                'id' => 90,
                'code' => NULL,
                'oldname' => 'ATENEO DE MANILA UNIVERSITY',
                'campus' => 'MAIN',
                'address' => 'KATIPUNAN AVE., LOYOLA HEIGHTS',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 37,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '137404000',
                'province_code' => '170000000',
                'region_code' => '130000000',
                'assigned_region' => '130000000',
                'created_at' => '2024-01-26 23:14:14',
                'updated_at' => '2024-01-26 23:14:14',
            ),
            90 => 
            array (
                'id' => 91,
                'code' => NULL,
                'oldname' => 'ATENEO DE NAGA UNIVERSITY, INC.',
                'campus' => 'MAIN',
                'address' => 'BAGUMBAYAN SUR',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 38,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '051724000',
                'province_code' => '051700000',
                'region_code' => '050000000',
                'assigned_region' => '050000000',
                'created_at' => '2024-01-26 23:15:04',
                'updated_at' => '2024-01-26 23:15:04',
            ),
            91 => 
            array (
                'id' => 92,
                'code' => NULL,
                'oldname' => 'ATENEO DE ZAMBOANGA UNIVERSITY',
                'campus' => 'MAIN',
                'address' => 'LA PURISIMA ST.',
                'is_main' => 0,
                'is_alone' => 1,
                'is_active' => 1,
                'school_id' => 39,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097332000',
                'province_code' => '097300000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2024-01-26 23:16:09',
                'updated_at' => '2024-01-26 23:16:09',
            ),
            92 => 
            array (
                'id' => 93,
                'code' => NULL,
                'oldname' => 'AURORA STATE COLLEGE OF TECHNOLOGY-MAIN',
                'campus' => 'MAIN',
                'address' => 'ZABALI',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 40,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '037701000',
                'province_code' => '037700000',
                'region_code' => '030000000',
                'assigned_region' => '030000000',
                'created_at' => '2024-01-26 23:18:14',
                'updated_at' => '2024-01-26 23:18:14',
            ),
            93 => 
            array (
                'id' => 94,
                'code' => NULL,
                'oldname' => 'AURORA STATE COLLEGE OF TECHNOLOGY-CASIGURAN',
                'campus' => 'CASIGURAN',
                'address' => 'ESTEVES CAMPUS',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 40,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '037702000',
                'province_code' => '037700000',
                'region_code' => '030000000',
                'assigned_region' => '030000000',
                'created_at' => '2024-01-26 23:18:50',
                'updated_at' => '2024-01-26 23:18:50',
            ),
            94 => 
            array (
                'id' => 95,
                'code' => NULL,
                'oldname' => 'AURORA STATE COLLEGE OF TECHNOLOGY-MARIA AURORA',
                'campus' => 'MARIA AURORA',
                'address' => 'BAZAL',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'school_id' => 40,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '037707000',
                'province_code' => '037700000',
                'region_code' => '030000000',
                'assigned_region' => '030000000',
                'created_at' => '2024-01-26 23:19:23',
                'updated_at' => '2024-01-26 23:19:23',
            ),
        ));
        
        
    }
}