<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ScholarProfilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('scholar_profiles')->delete();
        
        \DB::table('scholar_profiles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'account_no' => NULL,
                'email' => 'eliseanastacio06@gmail.com',
                'firstname' => 'Cassandra Elise',
                'lastname' => 'Anastacio',
                'middlename' => 'Mulato',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9659238636',
                'birthday' => '2003-01-06',
                'is_completed' => 1,
                'scholar_id' => 1,
                'created_at' => '2024-02-05 11:04:06',
                'updated_at' => '2024-02-05 11:04:06',
            ),
            1 => 
            array (
                'id' => 2,
                'account_no' => NULL,
                'email' => 'angelinajade1201@gmail.com',
                'firstname' => 'Angelina Jade',
                'lastname' => 'Beralde',
                'middlename' => NULL,
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9958870712',
                'birthday' => '2002-12-01',
                'is_completed' => 1,
                'scholar_id' => 2,
                'created_at' => '2024-02-05 11:05:35',
                'updated_at' => '2024-02-05 11:05:35',
            ),
            2 => 
            array (
                'id' => 3,
                'account_no' => NULL,
                'email' => 'canaoleo@gmail.com',
                'firstname' => 'Leomar',
                'lastname' => 'Canao',
                'middlename' => 'Ohina',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9550324128',
                'birthday' => '2003-02-04',
                'is_completed' => 1,
                'scholar_id' => 3,
                'created_at' => '2024-02-05 11:05:53',
                'updated_at' => '2024-02-05 11:05:53',
            ),
            3 => 
            array (
                'id' => 4,
                'account_no' => NULL,
                'email' => 'vivien.odg@gmail.com',
                'firstname' => 'Vivien',
                'lastname' => 'De Gracia',
                'middlename' => 'Orejodos',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9672061108',
                'birthday' => '2000-10-11',
                'is_completed' => 1,
                'scholar_id' => 4,
                'created_at' => '2024-02-05 11:06:20',
                'updated_at' => '2024-02-05 11:06:20',
            ),
            4 => 
            array (
                'id' => 5,
                'account_no' => NULL,
                'email' => 'shankhyledenisonestrada@gmail.com',
                'firstname' => 'Shan Khyle',
                'lastname' => 'Estrada',
                'middlename' => 'Denison',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9451830519',
                'birthday' => '2003-03-27',
                'is_completed' => 1,
                'scholar_id' => 5,
                'created_at' => '2024-02-05 11:06:54',
                'updated_at' => '2024-02-05 11:06:54',
            ),
            5 => 
            array (
                'id' => 6,
                'account_no' => NULL,
                'email' => 'itsianferolino@gmail.com',
                'firstname' => 'Ian Jay',
                'lastname' => 'Ferolino',
                'middlename' => 'Sumingit',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9700775325',
                'birthday' => '2002-05-02',
                'is_completed' => 1,
                'scholar_id' => 6,
                'created_at' => '2024-02-05 11:07:32',
                'updated_at' => '2024-02-05 11:07:32',
            ),
            6 => 
            array (
                'id' => 7,
                'account_no' => NULL,
                'email' => 'lubatonchristine17@gmail.com',
                'firstname' => 'Christine',
                'lastname' => 'Lubaton',
                'middlename' => 'Gelacio',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9269865562',
                'birthday' => '2003-04-07',
                'is_completed' => 1,
                'scholar_id' => 7,
                'created_at' => '2024-02-05 11:07:51',
                'updated_at' => '2024-02-05 11:07:51',
            ),
            7 => 
            array (
                'id' => 8,
                'account_no' => NULL,
                'email' => 'pershiapajiji21@gmail.com',
                'firstname' => 'Pershia',
                'lastname' => 'Pajiji',
                'middlename' => 'Abdurajak',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9178253971',
                'birthday' => '2003-11-21',
                'is_completed' => 1,
                'scholar_id' => 8,
                'created_at' => '2024-02-05 11:08:12',
                'updated_at' => '2024-02-05 11:08:12',
            ),
            8 => 
            array (
                'id' => 9,
                'account_no' => NULL,
                'email' => 'qb202100549@wmsu.edu.ph',
                'firstname' => 'Al-rafe',
                'lastname' => 'Bravo',
                'middlename' => 'Mama',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9266597075',
                'birthday' => '2002-08-12',
                'is_completed' => 1,
                'scholar_id' => 9,
                'created_at' => '2024-02-05 11:08:48',
                'updated_at' => '2024-02-05 11:08:48',
            ),
            9 => 
            array (
                'id' => 10,
                'account_no' => NULL,
                'email' => 'estrada.sabal.amira@gmail.com',
                'firstname' => 'Amira',
                'lastname' => 'Estrada',
                'middlename' => 'Sabal',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9064450457',
                'birthday' => '2003-07-13',
                'is_completed' => 1,
                'scholar_id' => 10,
                'created_at' => '2024-02-05 11:09:17',
                'updated_at' => '2024-02-05 11:09:17',
            ),
            10 => 
            array (
                'id' => 11,
                'account_no' => NULL,
                'email' => 'basiladrianeb@gmail.com',
                'firstname' => 'Basil Adriane',
                'lastname' => 'Laput',
                'middlename' => 'Chidrome',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9700730768',
                'birthday' => '2002-09-21',
                'is_completed' => 1,
                'scholar_id' => 11,
                'created_at' => '2024-02-05 11:09:44',
                'updated_at' => '2024-02-05 11:09:44',
            ),
            11 => 
            array (
                'id' => 12,
                'account_no' => NULL,
                'email' => 'aseradost19@gmail.com',
                'firstname' => 'Aishah',
                'lastname' => 'Sera',
                'middlename' => 'Sulay',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9271741861',
                'birthday' => '2003-10-06',
                'is_completed' => 1,
                'scholar_id' => 12,
                'created_at' => '2024-02-05 11:10:05',
                'updated_at' => '2024-02-05 11:10:05',
            ),
            12 => 
            array (
                'id' => 13,
                'account_no' => NULL,
                'email' => 'cdentang626@gmail.com',
                'firstname' => 'Christian Deniel',
                'lastname' => 'Tang',
                'middlename' => 'Guerrero',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9457237196',
                'birthday' => '2003-11-19',
                'is_completed' => 1,
                'scholar_id' => 13,
                'created_at' => '2024-02-05 11:10:32',
                'updated_at' => '2024-02-05 11:10:32',
            ),
            13 => 
            array (
                'id' => 14,
                'account_no' => NULL,
                'email' => 'joshuaalbay16@gmail.com',
                'firstname' => 'Joshua Angel',
                'lastname' => 'Albay',
                'middlename' => 'Caraecle',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9364404937',
                'birthday' => '2004-12-16',
                'is_completed' => 1,
                'scholar_id' => 14,
                'created_at' => '2024-02-05 11:11:47',
                'updated_at' => '2024-02-05 11:11:47',
            ),
            14 => 
            array (
                'id' => 15,
                'account_no' => NULL,
                'email' => 'allarexdaniel123@gmail.com',
                'firstname' => 'Rex Daniel',
                'lastname' => 'Alla',
                'middlename' => 'Sarmiento',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9261839592',
                'birthday' => '2004-07-26',
                'is_completed' => 1,
                'scholar_id' => 15,
                'created_at' => '2024-02-05 11:12:15',
                'updated_at' => '2024-02-05 11:12:15',
            ),
            15 => 
            array (
                'id' => 16,
                'account_no' => NULL,
                'email' => 'aquinoruainihashim@gmail.com',
                'firstname' => 'Ruaini',
                'lastname' => 'Aquino',
                'middlename' => 'Hashim',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9979429993',
                'birthday' => '2005-07-19',
                'is_completed' => 1,
                'scholar_id' => 16,
                'created_at' => '2024-02-05 11:12:52',
                'updated_at' => '2024-02-05 11:12:52',
            ),
            16 => 
            array (
                'id' => 17,
                'account_no' => NULL,
                'email' => 'richessminique357@gmail.com',
                'firstname' => 'Amaniy',
                'lastname' => 'Ayaon',
                'middlename' => 'Tandico',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9653348848',
                'birthday' => '2005-09-13',
                'is_completed' => 1,
                'scholar_id' => 17,
                'created_at' => '2024-02-05 11:13:49',
                'updated_at' => '2024-02-05 11:13:49',
            ),
            17 => 
            array (
                'id' => 18,
                'account_no' => NULL,
                'email' => 'tyronepareno27@gmail.com',
                'firstname' => 'Leiann Tyrone',
                'lastname' => 'Capala',
                'middlename' => 'ParreÑo',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9218561974',
                'birthday' => '2005-09-27',
                'is_completed' => 1,
                'scholar_id' => 18,
                'created_at' => '2024-02-05 11:14:09',
                'updated_at' => '2024-02-05 11:14:09',
            ),
            18 => 
            array (
                'id' => 19,
                'account_no' => NULL,
                'email' => 'denzmath110@gmail.com',
                'firstname' => 'Dennis',
                'lastname' => 'Dayaganon',
                'middlename' => 'Montalba',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9650581243',
                'birthday' => '2004-11-10',
                'is_completed' => 1,
                'scholar_id' => 19,
                'created_at' => '2024-02-05 11:14:47',
                'updated_at' => '2024-02-05 11:14:47',
            ),
            19 => 
            array (
                'id' => 20,
                'account_no' => NULL,
                'email' => 'dellavakenvinzel@gmail.com',
                'firstname' => 'Ken Vinzel',
                'lastname' => 'Dellava',
                'middlename' => 'Ebol',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9552142342',
                'birthday' => '2005-02-21',
                'is_completed' => 1,
                'scholar_id' => 20,
                'created_at' => '2024-02-05 11:15:07',
                'updated_at' => '2024-02-05 11:15:07',
            ),
            20 => 
            array (
                'id' => 21,
                'account_no' => NULL,
                'email' => 'kristylirramae22@gmail.com',
                'firstname' => 'Kristyl Irra Mae',
                'lastname' => 'Elcamel',
                'middlename' => 'Calasang',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9089725775',
                'birthday' => '2004-08-22',
                'is_completed' => 1,
                'scholar_id' => 21,
                'created_at' => '2024-02-05 11:15:39',
                'updated_at' => '2024-02-05 11:15:39',
            ),
            21 => 
            array (
                'id' => 22,
                'account_no' => NULL,
                'email' => 'ellicaarnold4official@gmail.com',
                'firstname' => 'Arnold',
                'lastname' => 'Ellica',
                'middlename' => 'Basilio',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9274933953',
                'birthday' => '2004-07-10',
                'is_completed' => 1,
                'scholar_id' => 22,
                'created_at' => '2024-02-05 11:16:01',
                'updated_at' => '2024-02-05 11:16:01',
            ),
            22 => 
            array (
                'id' => 23,
                'account_no' => NULL,
                'email' => 'enriquezaprilmae44@gmail.com',
                'firstname' => 'April Mae',
                'lastname' => 'Enriquez',
                'middlename' => 'Maruji',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => 'n/a',
                'birthday' => '2005-04-26',
                'is_completed' => 1,
                'scholar_id' => 23,
                'created_at' => '2024-02-05 11:16:24',
                'updated_at' => '2024-02-05 11:16:24',
            ),
            23 => 
            array (
                'id' => 24,
                'account_no' => NULL,
                'email' => 'enriquezrose719@gmail.com',
                'firstname' => 'April Rose',
                'lastname' => 'Enriquez',
                'middlename' => 'Maruji',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9555905961',
                'birthday' => '2005-04-26',
                'is_completed' => 1,
                'scholar_id' => 24,
                'created_at' => '2024-02-05 11:16:35',
                'updated_at' => '2024-02-05 11:16:35',
            ),
            24 => 
            array (
                'id' => 25,
                'account_no' => NULL,
                'email' => 'kimmyvictus@gmail.com',
                'firstname' => 'Ryan',
                'lastname' => 'Escodero',
                'middlename' => 'Painaga',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9364635344',
                'birthday' => '2005-06-20',
                'is_completed' => 1,
                'scholar_id' => 25,
                'created_at' => '2024-02-05 11:16:56',
                'updated_at' => '2024-02-05 11:16:56',
            ),
            25 => 
            array (
                'id' => 26,
                'account_no' => NULL,
                'email' => 'jamesmarkescorial@gmail.com',
                'firstname' => 'James Mark',
                'lastname' => 'Escorial',
                'middlename' => 'Ursabia',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9380259746',
                'birthday' => '2004-08-24',
                'is_completed' => 1,
                'scholar_id' => 26,
                'created_at' => '2024-02-05 11:17:40',
                'updated_at' => '2024-02-05 11:17:40',
            ),
            26 => 
            array (
                'id' => 27,
                'account_no' => NULL,
                'email' => 'arthon.godito@gmail.com',
                'firstname' => 'Lito Arthon',
                'lastname' => 'Godito',
                'middlename' => 'Recamara',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9212505350',
                'birthday' => '2004-11-06',
                'is_completed' => 1,
                'scholar_id' => 27,
                'created_at' => '2024-02-05 11:19:57',
                'updated_at' => '2024-02-05 11:19:57',
            ),
            27 => 
            array (
                'id' => 28,
                'account_no' => NULL,
                'email' => 'handuganginoandrie@gmail.com',
                'firstname' => 'Gino Andrie',
                'lastname' => 'Handugan',
                'middlename' => 'Ricardo',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9479571759',
                'birthday' => '2004-11-30',
                'is_completed' => 1,
                'scholar_id' => 28,
                'created_at' => '2024-02-05 11:20:24',
                'updated_at' => '2024-02-05 11:20:24',
            ),
            28 => 
            array (
                'id' => 29,
                'account_no' => NULL,
                'email' => 'princeslumawas@gmail.com',
                'firstname' => 'Princes Nel Ann',
                'lastname' => 'Lumawas',
                'middlename' => 'Calunod',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9673657869',
                'birthday' => '2005-06-29',
                'is_completed' => 1,
                'scholar_id' => 29,
                'created_at' => '2024-02-05 11:20:47',
                'updated_at' => '2024-02-05 11:20:47',
            ),
            29 => 
            array (
                'id' => 30,
                'account_no' => NULL,
                'email' => 'kenmac06.km@gmail.com',
                'firstname' => 'Ken',
                'lastname' => 'Macaraeg',
                'middlename' => 'Olaivar',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9184866797',
                'birthday' => '2005-01-06',
                'is_completed' => 1,
                'scholar_id' => 30,
                'created_at' => '2024-02-05 11:21:13',
                'updated_at' => '2024-02-05 11:21:13',
            ),
            30 => 
            array (
                'id' => 31,
                'account_no' => NULL,
                'email' => 'mishmalun@gmail.com',
                'firstname' => 'Mishal',
                'lastname' => 'Malun',
                'middlename' => 'Sejera',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9214002016',
                'birthday' => '2004-11-16',
                'is_completed' => 1,
                'scholar_id' => 31,
                'created_at' => '2024-02-05 11:21:57',
                'updated_at' => '2024-02-05 11:21:57',
            ),
            31 => 
            array (
                'id' => 32,
                'account_no' => NULL,
                'email' => 'cythelmanait@gmail.com',
                'firstname' => 'Cythel Marie',
                'lastname' => 'Manait',
                'middlename' => 'Rusiana',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9264325654',
                'birthday' => '2005-07-09',
                'is_completed' => 1,
                'scholar_id' => 32,
                'created_at' => '2024-02-05 11:22:23',
                'updated_at' => '2024-02-05 11:22:23',
            ),
            32 => 
            array (
                'id' => 33,
                'account_no' => NULL,
                'email' => 'mejoradahazelann@gmail.com',
                'firstname' => 'Hazel Ann',
                'lastname' => 'Mejorada',
                'middlename' => 'Clarion',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9168489705',
                'birthday' => '2005-06-13',
                'is_completed' => 1,
                'scholar_id' => 33,
                'created_at' => '2024-02-05 11:22:51',
                'updated_at' => '2024-02-05 11:22:51',
            ),
            33 => 
            array (
                'id' => 34,
                'account_no' => NULL,
                'email' => 'royajanemontiel@gmail.com',
                'firstname' => 'Roya Jane',
                'lastname' => 'Montiel',
                'middlename' => 'Butalid',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9550577251',
                'birthday' => '2005-10-23',
                'is_completed' => 1,
                'scholar_id' => 34,
                'created_at' => '2024-02-05 11:23:27',
                'updated_at' => '2024-02-05 11:23:27',
            ),
            34 => 
            array (
                'id' => 35,
                'account_no' => NULL,
                'email' => 'cyd.oral25@gmail.com',
                'firstname' => 'Clarence James',
                'lastname' => 'Oral',
                'middlename' => 'Dunggay',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9203531940',
                'birthday' => '2005-05-25',
                'is_completed' => 1,
                'scholar_id' => 35,
                'created_at' => '2024-02-05 11:24:29',
                'updated_at' => '2024-02-05 11:24:29',
            ),
            35 => 
            array (
                'id' => 36,
                'account_no' => NULL,
                'email' => 'jp.jasper01904@gmail.com',
                'firstname' => 'Jasper',
                'lastname' => 'OraÑola',
                'middlename' => 'Pangilayan',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9518460189',
                'birthday' => '2004-09-01',
                'is_completed' => 1,
                'scholar_id' => 36,
                'created_at' => '2024-02-05 11:24:59',
                'updated_at' => '2024-02-05 11:24:59',
            ),
            36 => 
            array (
                'id' => 37,
                'account_no' => NULL,
                'email' => 'porillo2004@gmail.com',
                'firstname' => 'Joshua',
                'lastname' => 'Porillo',
                'middlename' => 'Bartolo',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9383093931',
                'birthday' => '2004-12-25',
                'is_completed' => 1,
                'scholar_id' => 37,
                'created_at' => '2024-02-05 11:25:23',
                'updated_at' => '2024-02-05 11:25:23',
            ),
            37 => 
            array (
                'id' => 38,
                'account_no' => NULL,
                'email' => 'euwanprias44@gmail.com',
                'firstname' => 'Euwan Tyrone',
                'lastname' => 'Prias',
                'middlename' => 'Baugbog',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9654008462',
                'birthday' => '2005-05-16',
                'is_completed' => 1,
                'scholar_id' => 38,
                'created_at' => '2024-02-05 11:25:49',
                'updated_at' => '2024-02-05 11:25:49',
            ),
            38 => 
            array (
                'id' => 39,
                'account_no' => NULL,
                'email' => 'asianthyjeannin@gmail.com',
                'firstname' => 'Asianthy Jeannin',
                'lastname' => 'Santillan',
                'middlename' => 'Andico',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9558120347',
                'birthday' => '2004-08-20',
                'is_completed' => 1,
                'scholar_id' => 39,
                'created_at' => '2024-02-05 11:26:11',
                'updated_at' => '2024-02-05 11:26:11',
            ),
            39 => 
            array (
                'id' => 40,
                'account_no' => NULL,
                'email' => 'jeanniza.sulit@gmail.com',
                'firstname' => 'Rudjean Ruth',
                'lastname' => 'Sulit',
                'middlename' => 'Reluya',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9293694553',
                'birthday' => '2004-04-01',
                'is_completed' => 1,
                'scholar_id' => 40,
                'created_at' => '2024-02-05 11:26:41',
                'updated_at' => '2024-02-05 11:26:41',
            ),
            40 => 
            array (
                'id' => 41,
                'account_no' => NULL,
                'email' => 'tabanagjimbert@gmail.com',
                'firstname' => 'Jimbert',
                'lastname' => 'TabaÑag',
                'middlename' => 'Laquinon',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9816937807',
                'birthday' => '2004-08-25',
                'is_completed' => 1,
                'scholar_id' => 41,
                'created_at' => '2024-02-05 11:27:34',
                'updated_at' => '2024-02-05 11:27:34',
            ),
            41 => 
            array (
                'id' => 42,
                'account_no' => NULL,
                'email' => 'danieltipohian2505@gmail.com',
                'firstname' => 'Daniel Ian',
                'lastname' => 'Tipoh',
                'middlename' => 'Gener',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9074601649',
                'birthday' => '2005-02-25',
                'is_completed' => 1,
                'scholar_id' => 42,
                'created_at' => '2024-02-05 11:27:51',
                'updated_at' => '2024-02-05 11:27:51',
            ),
            42 => 
            array (
                'id' => 43,
                'account_no' => NULL,
                'email' => 'toribiovincejoriz@gmail.com',
                'firstname' => 'Vince Joriz',
                'lastname' => 'Toribio',
                'middlename' => 'Santillan',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9361016164',
                'birthday' => '2005-06-19',
                'is_completed' => 1,
                'scholar_id' => 43,
                'created_at' => '2024-02-05 11:28:13',
                'updated_at' => '2024-02-05 11:28:13',
            ),
            43 => 
            array (
                'id' => 44,
                'account_no' => NULL,
                'email' => 'hannahgracetulabing@gmail.com',
                'firstname' => 'Hannah Grace',
                'lastname' => 'Tulabing',
                'middlename' => 'Saluta',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9097207890',
                'birthday' => '2005-02-24',
                'is_completed' => 1,
                'scholar_id' => 44,
                'created_at' => '2024-02-05 11:28:36',
                'updated_at' => '2024-02-05 11:28:36',
            ),
            44 => 
            array (
                'id' => 45,
                'account_no' => NULL,
                'email' => 'ms.jasmineungab@gmail.com',
                'firstname' => 'Jasmine Marie',
                'lastname' => 'Ungab',
                'middlename' => 'Macalisan',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9060769830',
                'birthday' => '2005-10-01',
                'is_completed' => 1,
                'scholar_id' => 45,
                'created_at' => '2024-02-05 11:28:54',
                'updated_at' => '2024-02-05 11:28:54',
            ),
            45 => 
            array (
                'id' => 46,
                'account_no' => NULL,
                'email' => 'altkian2@gmail.com',
                'firstname' => 'Nadzwa',
                'lastname' => 'Usman',
                'middlename' => 'Paradji',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9751762529',
                'birthday' => '2005-10-28',
                'is_completed' => 1,
                'scholar_id' => 46,
                'created_at' => '2024-02-05 11:29:12',
                'updated_at' => '2024-02-05 11:29:12',
            ),
            46 => 
            array (
                'id' => 47,
                'account_no' => NULL,
                'email' => 'anhelmariealabata@gmail.com',
                'firstname' => 'Angel Marie',
                'lastname' => 'Alabata',
                'middlename' => 'Rubia',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9752771135',
                'birthday' => '2005-07-21',
                'is_completed' => 1,
                'scholar_id' => 47,
                'created_at' => '2024-02-05 11:29:30',
                'updated_at' => '2024-02-05 11:29:30',
            ),
            47 => 
            array (
                'id' => 48,
                'account_no' => NULL,
                'email' => 'therealalphavet@gmail.com',
                'firstname' => 'Ahmed Johnny-feigedhar',
                'lastname' => 'Alpha',
                'middlename' => 'Kalinggalan',
                'suffix' => 'III',
                'sex' => 'M',
                'contact_no' => '9656135103',
                'birthday' => '2004-12-02',
                'is_completed' => 1,
                'scholar_id' => 48,
                'created_at' => '2024-02-05 11:29:51',
                'updated_at' => '2024-02-05 11:29:51',
            ),
            48 => 
            array (
                'id' => 49,
                'account_no' => NULL,
                'email' => 'micokleinldelosreyes@gmail.com',
                'firstname' => 'Mico Klein',
                'lastname' => 'Delos Reyes',
                'middlename' => 'Lim',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9925030710',
                'birthday' => '2004-12-14',
                'is_completed' => 1,
                'scholar_id' => 49,
                'created_at' => '2024-02-05 11:30:07',
                'updated_at' => '2024-02-05 11:30:07',
            ),
            49 => 
            array (
                'id' => 50,
                'account_no' => NULL,
                'email' => 'bridgetfernandez19@gmail.com',
                'firstname' => 'Maria Bridget',
                'lastname' => 'Fernandez',
                'middlename' => 'Lacastesantos',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9663717107',
                'birthday' => '2005-02-19',
                'is_completed' => 1,
                'scholar_id' => 50,
                'created_at' => '2024-02-05 11:30:24',
                'updated_at' => '2024-02-05 11:30:24',
            ),
            50 => 
            array (
                'id' => 51,
                'account_no' => NULL,
                'email' => 'irenelucilleee@gmail.com',
                'firstname' => 'Irene Lucille',
                'lastname' => 'Garcia',
                'middlename' => 'Go',
                'suffix' => NULL,
                'sex' => 'F',
                'contact_no' => '9677212599',
                'birthday' => '2004-05-11',
                'is_completed' => 1,
                'scholar_id' => 51,
                'created_at' => '2024-02-05 11:30:55',
                'updated_at' => '2024-02-05 11:30:55',
            ),
            51 => 
            array (
                'id' => 52,
                'account_no' => NULL,
                'email' => 'hasimshariffkhalifa@gmail.com',
                'firstname' => 'Shariff Khalifa',
                'lastname' => 'Hasim',
                'middlename' => 'Ismael',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9817061022',
                'birthday' => '2005-06-08',
                'is_completed' => 1,
                'scholar_id' => 52,
                'created_at' => '2024-02-05 11:31:18',
                'updated_at' => '2024-02-05 11:31:18',
            ),
            52 => 
            array (
                'id' => 53,
                'account_no' => NULL,
                'email' => 'almeqdhadjocutan@gmail.com',
                'firstname' => 'Al Meqdhad Ibrahim',
                'lastname' => 'Jocutan',
                'middlename' => 'Braza',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9554501035',
                'birthday' => '2005-02-20',
                'is_completed' => 1,
                'scholar_id' => 53,
                'created_at' => '2024-02-05 11:31:36',
                'updated_at' => '2024-02-05 11:31:36',
            ),
            53 => 
            array (
                'id' => 54,
                'account_no' => NULL,
                'email' => 'harveycharlex@gmail.com',
                'firstname' => 'Harvey Charles',
                'lastname' => 'Magsayo',
                'middlename' => 'Caindug',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9517478230',
                'birthday' => '2004-06-25',
                'is_completed' => 1,
                'scholar_id' => 54,
                'created_at' => '2024-02-05 11:31:57',
                'updated_at' => '2024-02-05 11:31:57',
            ),
            54 => 
            array (
                'id' => 55,
                'account_no' => NULL,
                'email' => 'nobnoj20@gmail.com',
                'firstname' => 'Jon Antonee',
                'lastname' => 'Orillineda',
                'middlename' => 'Acorin',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9561390937',
                'birthday' => '2004-07-17',
                'is_completed' => 1,
                'scholar_id' => 55,
                'created_at' => '2024-02-05 11:32:18',
                'updated_at' => '2024-02-05 11:32:18',
            ),
            55 => 
            array (
                'id' => 56,
                'account_no' => NULL,
                'email' => 'arne.xe54@gmail.com',
                'firstname' => 'Arne Christian John',
                'lastname' => 'Senon',
                'middlename' => 'Dela PeÑa',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9654018892',
                'birthday' => '2005-12-06',
                'is_completed' => 1,
                'scholar_id' => 56,
                'created_at' => '2024-02-05 11:32:48',
                'updated_at' => '2024-02-05 11:32:48',
            ),
            56 => 
            array (
                'id' => 57,
                'account_no' => NULL,
                'email' => 'tubilmarc@gmail.com',
                'firstname' => 'Marc Lorience',
                'lastname' => 'Tubil',
                'middlename' => 'Item',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9919350594',
                'birthday' => '2004-12-14',
                'is_completed' => 1,
                'scholar_id' => 57,
                'created_at' => '2024-02-05 11:33:04',
                'updated_at' => '2024-02-05 11:33:04',
            ),
            57 => 
            array (
                'id' => 58,
                'account_no' => NULL,
                'email' => 'renseebanez@gmail.com',
                'firstname' => 'Rensee Louie',
                'lastname' => 'YbaÑez',
                'middlename' => 'Guevarra',
                'suffix' => NULL,
                'sex' => 'M',
                'contact_no' => '9464764069',
                'birthday' => '2004-09-20',
                'is_completed' => 1,
                'scholar_id' => 58,
                'created_at' => '2024-02-05 11:33:23',
                'updated_at' => '2024-02-05 11:33:23',
            ),
        ));
        
        
    }
}