<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SchoolsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('schools')->delete();
        
        \DB::table('schools')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'UNIVERSITY OF ABRA',
                'shortcut' => 'UA',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 14:20:26',
                'updated_at' => '2024-01-26 14:20:26',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'ABUYOG COMMUNITY COLLEGE',
                'shortcut' => 'ACC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 3,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 14:31:26',
                'updated_at' => '2024-01-26 14:31:26',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'ACES POLYTECHNIC COLLEGE',
                'shortcut' => 'APC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 14:36:17',
                'updated_at' => '2024-01-26 14:36:17',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'ACES TAGUM COLLEGE, INC.',
                'shortcut' => 'ATC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 14:40:18',
                'updated_at' => '2024-01-26 14:40:18',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'ACLC COLLEGE',
                'shortcut' => 'AC',
                'combiner' => 'OF',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 14:45:24',
                'updated_at' => '2024-01-26 14:45:24',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'ACSI COLLEGE ILOILO',
                'shortcut' => 'ACI',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 14:58:06',
                'updated_at' => '2024-01-26 14:58:06',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'ACTS COMPUTER COLLEGE',
                'shortcut' => 'ACC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 15:01:04',
                'updated_at' => '2024-01-26 15:01:04',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'ADAMSON UNIVERSITY',
                'shortcut' => 'ADU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 15:03:10',
                'updated_at' => '2024-01-26 15:03:10',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'ADIONG MEMORIAL POLYTECHNIC STATE COLLEGE',
                'shortcut' => 'AMSC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 15:05:14',
                'updated_at' => '2024-01-26 15:05:14',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'ADVENTIST MEDICAL CENTER COLLEGE',
                'shortcut' => 'AMCC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 15:07:45',
                'updated_at' => '2024-01-26 15:07:45',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'ADVENTIST UNIVERSITY OF THE PHILIPPINES',
                'shortcut' => 'AUP',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 15:09:31',
                'updated_at' => '2024-01-26 15:09:31',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'AEMILIANUM COLLEGE, INC.',
                'shortcut' => 'ACI',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 15:13:26',
                'updated_at' => '2024-01-26 15:13:26',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'AGO MEDICAL AND EDUCATIONAL CENTER - BICOL CHRISTIAN COLLEGE OF MEDICINE',
                'shortcut' => 'AMEC-BCCM',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 15:18:56',
                'updated_at' => '2024-01-26 15:18:56',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'AGUSAN DEL SUR STATE COLLEGE OF AGRICULTURE AND TECHNOLOGY',
                'shortcut' => 'ASSCAT',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 16:01:35',
                'updated_at' => '2024-01-26 16:01:35',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'AKLAN CATHOLIC COLLEGE',
                'shortcut' => 'ACC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 16:03:20',
                'updated_at' => '2024-01-26 16:03:20',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'AKLAN POLYTECHNIC COLLEGE',
                'shortcut' => 'APC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 16:05:51',
                'updated_at' => '2024-01-26 16:05:51',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'AKLAN STATE UNIVERSITY',
                'shortcut' => 'ASU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 16:07:37',
                'updated_at' => '2024-01-26 16:07:37',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'ALDERGATE COLLEGE, INC.',
                'shortcut' => 'AC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 16:11:41',
                'updated_at' => '2024-01-26 16:11:41',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'AMA COMPUTER COLLEGE',
                'shortcut' => 'AMA',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 16:15:52',
                'updated_at' => '2024-01-26 16:15:52',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'AMA COMPUTER LEARNING CENTER',
                'shortcut' => 'ACLC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:10:49',
                'updated_at' => '2024-01-26 22:10:49',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'AMA UNIVERSITY',
                'shortcut' => 'AMA',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:14:16',
                'updated_at' => '2024-01-26 22:14:16',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'AMANDO COPE COLLEGE',
                'shortcut' => 'ACC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:21:20',
                'updated_at' => '2024-01-26 22:21:20',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'ANDRES BONIFACIO COLLEGE',
                'shortcut' => 'ABC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:24:15',
                'updated_at' => '2024-01-26 22:24:15',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'ANGELES UNIVERSITY FOUNDATION',
                'shortcut' => 'AUF',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:25:34',
                'updated_at' => '2024-01-26 22:25:34',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'APAYAO STATE COLLEGE',
                'shortcut' => 'ASC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:29:33',
                'updated_at' => '2024-01-26 22:29:33',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'ARELLANO UNIVERSITY',
                'shortcut' => 'AU',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:34:55',
                'updated_at' => '2024-01-26 22:34:55',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'ARRIESGADO COLLEGE FOUNDATION, INC.',
                'shortcut' => 'ACF',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:38:45',
                'updated_at' => '2024-01-26 22:38:45',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'ASIA PACIFIC COLLEGE',
                'shortcut' => 'APC',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:40:36',
                'updated_at' => '2024-01-26 22:40:36',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'ASIA PACIFIC COLLEGE OF ADVANCE STUDIES',
                'shortcut' => 'APC-AS',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:41:33',
                'updated_at' => '2024-01-26 22:41:33',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'ASIA TECHNOLOGICAL SCHOOL OF SCIENCE AND ARTS',
                'shortcut' => 'ASIATECH',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:44:25',
                'updated_at' => '2024-01-26 22:44:25',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'ASIAN COLLEGE',
                'shortcut' => 'AC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 22:57:29',
                'updated_at' => '2024-01-26 22:57:29',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'ASIAN COLLEGE OF TECHNOLOGY - INTERNATIONAL EDUCATIONAL FOUNDATION',
                'shortcut' => 'ACT-IEF',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:00:30',
                'updated_at' => '2024-01-26 23:00:30',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'ASIAN COLLEGE FOUNDATION',
                'shortcut' => 'ACF',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:01:29',
                'updated_at' => '2024-01-26 23:01:29',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'ASSUMPTION COLLEGE',
                'shortcut' => 'AC',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:04:46',
                'updated_at' => '2024-01-26 23:04:46',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'ASYNCHRONOUS SYSTEMS AND COMPUTER INFORMATION INSTITUTE',
                'shortcut' => 'ASCII',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:09:19',
                'updated_at' => '2024-01-26 23:09:19',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'ATENEO DE DAVAO UNIVERSITY',
                'shortcut' => 'ADDU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:11:59',
                'updated_at' => '2024-01-26 23:11:59',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'ATENEO DE MANILA UNIVERSITY',
                'shortcut' => 'ADMU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:12:16',
                'updated_at' => '2024-01-26 23:12:16',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'ATENEO DE NAGA UNIVERSITY',
                'shortcut' => 'ADNU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:12:35',
                'updated_at' => '2024-01-26 23:12:35',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'ATENEO DE ZAMBOANGA UNIVERSITY',
                'shortcut' => 'ADZU',
                'combiner' => NULL,
                'avatar' => 'school.jpg',
                'class_id' => 40,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:12:49',
                'updated_at' => '2024-01-26 23:12:49',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'AURORA STATE COLLEGE OF TECHNOLOGY',
                'shortcut' => 'ASCT',
                'combiner' => '-',
                'avatar' => 'school.jpg',
                'class_id' => 2,
                'is_upsystem' => 0,
                'is_active' => 1,
                'created_at' => '2024-01-26 23:17:35',
                'updated_at' => '2024-01-26 23:17:35',
            ),
        ));
        
        
    }
}